---@meta
-- WoW widget API for the Lua language server.
-- AUTO-GENERATED by tools/generate_lua_definitions.lua from the ScriptObject
-- docs under tests/api-docs/blizzard. Do not edit by hand.
--
-- Every widget method lives on __WowWidget; the concrete widget types our
-- code references inherit it, so frame method calls and `---@return Frame`
-- style annotations resolve. Methods take optional params + a trailing
-- vararg so arg-count never false-positives.

---@class __WowWidget
local __WowWidget = {}

--- Adds a new breakpoint to the formatter.
---@param breakpoint? any
---@param ... any
function __WowWidget:AddBreakpoint(breakpoint, ...) end
---@param index? number
---@param light? any
---@param ... any
function __WowWidget:AddCharacterLight(index, light, ...) end
---@param index? number
---@param light? any
---@param ... any
function __WowWidget:AddLight(index, light, ...) end
---@param text? string
---@param colorR? number
---@param colorG? number
---@param colorB? number
---@param a? any
---@param messageID? number
---@param ... any
function __WowWidget:AddMessage(text, colorR, colorG, colorB, a, messageID, ...) end
---@param index? number
---@param light? any
---@param ... any
function __WowWidget:AddPetLight(index, light, ...) end
--- Adds a single point to the curve.
---@param x? number
---@param y? any
---@param ... any
function __WowWidget:AddPoint(x, y, ...) end
---@param unitTokenString? string
---@param asset? any
---@param width? number
---@param height? number
---@param r? number
---@param g? number
---@param b? number
---@param a? number
---@param sublayer? number
---@param showFacing? boolean
---@param ... any
function __WowWidget:AddUnit(unitTokenString, asset, width, height, r, g, b, a, sublayer, showFacing, ...) end
---@param x? number
---@param y? number
---@param ... any
function __WowWidget:AdjustPointsOffset(x, y, ...) end
---@param ... any
function __WowWidget:AdvanceTime(...) end
---@param texture? any
---@param snapshotID? number
---@param ... any
---@return boolean success
function __WowWidget:ApplySnapshot(texture, snapshotID, ...) end
---@param spellVisualKitID? number
---@param oneShot? boolean
---@param ... any
function __WowWidget:ApplySpellVisualKit(spellVisualKitID, oneShot, ...) end
--- Copies another duration object and assigns it to this one.
---@param other? any
---@param ... any
function __WowWidget:Assign(other, ...) end
---@param rider? any
---@param animation? any
---@param spellKitVisualID? number
---@param ... any
---@return boolean success
function __WowWidget:AttachToMount(rider, animation, spellKitVisualID, ...) end
---@param rider? any
---@param ... any
---@return number scale
function __WowWidget:CalculateMountScale(rider, ...) end
--- Returns true if the given number of seconds is within an appropriate range for approximated formatting.
---@param seconds? any
---@param ... any
---@return boolean canApproximate
function __WowWidget:CanApproximate(seconds, ...) end
--- Returns true if this nameplate permits changes to its hit-test points. Updates are normally blocked for tainted code during combat, except on the tick a unit is first assigned or when untainted code updates hit-test points on the same tick.
---@param ... any
---@return boolean canChangeHitTestPoints
function __WowWidget:CanChangeHitTestPoints(...) end
---@param ... any
---@return any moveRestriction
function __WowWidget:CanMove(...) end
---@param ... any
---@return any removalRestriction
function __WowWidget:CanRemove(...) end
---@param ... any
---@return any rotateRestriction
function __WowWidget:CanRotate(...) end
--- Returns true if the formatter can promote values to higher interval bands.
---@param ... any
---@return boolean canRound
function __WowWidget:CanRoundUpIntervals(...) end
--- Returns true if the formatter should round the final unit up rather than down.
---@param ... any
---@return boolean canRound
function __WowWidget:CanRoundUpLastUnit(...) end
---@param ... any
---@return boolean canSave
function __WowWidget:CanSaveTabardNow(...) end
---@param unit? any
---@param ... any
function __WowWidget:CanSetUnit(unit, ...) end
---@param ... any
function __WowWidget:CancelOpenCheckout(...) end
---@param ... any
function __WowWidget:Clear(...) end
--- Clears the anchor points that determine where the mouse interacts with the nameplate.
---@param ... any
function __WowWidget:ClearAllHitTestPoints(...) end
---@param ... any
function __WowWidget:ClearAllPoints(...) end
--- Removes all configured breakpoints from the formatter.
---@param ... any
function __WowWidget:ClearBreakpoints(...) end
---@param ... any
function __WowWidget:ClearColorWheelTexture(...) end
---@param ... any
function __WowWidget:ClearFocus(...) end
---@param ... any
function __WowWidget:ClearFog(...) end
---@param ... any
function __WowWidget:ClearModel(...) end
---@param point? any
---@param ... any
function __WowWidget:ClearPoint(point, ...) end
--- Removes all points from the curve. Evaluating an empty curve always yields a zero value.
---@param ... any
function __WowWidget:ClearPoints(...) end
---@param ... any
function __WowWidget:ClearPointsOffset(...) end
---@param ... any
function __WowWidget:ClearTransform(...) end
---@param ... any
function __WowWidget:ClearUnits(...) end
---@param ... any
function __WowWidget:CloseCheckout(...) end
--- Returns a new copy of this formatter.
---@param ... any
---@return any copy
function __WowWidget:Copy(...) end
---@param ... any
function __WowWidget:CopyExternalLink(...) end
---@param sourceFont? any
---@param ... any
function __WowWidget:CopyFontObject(sourceFont, ...) end
---@param name? string
---@param template? string
---@param ... any
function __WowWidget:CreateActor(name, template, ...) end
---@param name? string
---@param templateName? string
---@param ... any
---@return any group
function __WowWidget:CreateAnimationGroup(name, templateName, ...) end
---@param name? string
---@param templateName? string
---@param order? number
---@param ... any
---@return any point
function __WowWidget:CreateControlPoint(name, templateName, order, ...) end
---@param variationIndex? number
---@param delta? number
---@param ... any
function __WowWidget:CycleVariation(variationIndex, delta, ...) end
---@param ... any
function __WowWidget:DeleteCookies(...) end
---@param rider? any
---@param ... any
---@return boolean success
function __WowWidget:DetachFromMount(rider, ...) end
---@param ... any
function __WowWidget:Disable(...) end
---@param isAccessible? boolean
---@param ... any
function __WowWidget:Drag(isAccessible, ...) end
---@param ... any
function __WowWidget:DrawAll(...) end
---@param questID? number
---@param draw? boolean
---@param ... any
function __WowWidget:DrawBlob(questID, draw, ...) end
---@param ... any
function __WowWidget:DrawNone(...) end
---@param ... any
function __WowWidget:Dress(...) end
---@param invSlot? number
---@param ... any
function __WowWidget:DressPlayerSlot(invSlot, ...) end
---@param ... any
function __WowWidget:Enable(...) end
---@param enable? boolean
---@param ... any
function __WowWidget:EnableMerging(enable, ...) end
---@param enable? boolean
---@param ... any
function __WowWidget:EnableSmoothing(enable, ...) end
---@param enable? boolean
---@param ... any
function __WowWidget:EnableSubtitles(enable, ...) end
---@param itemID? number
---@param ... any
function __WowWidget:EquipItem(itemID, ...) end
--- Returns a calculated color value from the configured curve points.
---@param x? number
---@param ... any
---@return any y
function __WowWidget:Evaluate(x, ...) end
--- Calculates the percentage of current unit health and evaluates it against the supplied curve.
---@param curve? any
---@param ... any
---@return any result
function __WowWidget:EvaluateCurrentHealthPercent(curve, ...) end
--- Returns the unit count that a given number of seconds will use for formatting.
---@param seconds? any
---@param ... any
---@return number count
function __WowWidget:EvaluateDesiredUnitCount(seconds, ...) end
--- Calculates the elapsed duration in seconds and evaluates it against a supplied curve.
---@param curve? any
---@param modifier? any
---@param ... any
---@return any result
function __WowWidget:EvaluateElapsedDuration(curve, modifier, ...) end
--- Calculates the elapsed duration as a percentage value and evaluates it against a supplied curve.
---@param curve? any
---@param modifier? any
---@param ... any
---@return any result
function __WowWidget:EvaluateElapsedPercent(curve, modifier, ...) end
--- Returns the maximum interval band that a given number of seconds will use for formatting.
---@param seconds? any
---@param ... any
---@return any interval
function __WowWidget:EvaluateMaxInterval(seconds, ...) end
--- Returns the minimum interval band that a given number of seconds will use for formatting.
---@param seconds? any
---@param ... any
---@return any interval
function __WowWidget:EvaluateMinInterval(seconds, ...) end
--- Calculates the percentage of missing unit health and evaluates it against the supplied curve.
---@param curve? any
---@param ... any
---@return any result
function __WowWidget:EvaluateMissingHealthPercent(curve, ...) end
--- Calculates the remaining duration in seconds and evaluates it against a supplied curve.
---@param curve? any
---@param modifier? any
---@param ... any
---@return any result
function __WowWidget:EvaluateRemainingDuration(curve, modifier, ...) end
--- Calculates the remaining duration as a percentage value and evaluates it against a supplied curve.
---@param curve? any
---@param modifier? any
---@param ... any
---@return any result
function __WowWidget:EvaluateRemainingPercent(curve, modifier, ...) end
--- Calculates the total duration in seconds and evaluates it against a supplied curve.
---@param curve? any
---@param modifier? any
---@param ... any
---@return any result
function __WowWidget:EvaluateTotalDuration(curve, modifier, ...) end
--- Returns an unpacked calculated color value from the configured curve points.
---@param x? number
---@param ... any
---@return number yR
---@return number yG
---@return number yB
---@return number yA
function __WowWidget:EvaluateUnpacked(x, ...) end
---@param ... any
function __WowWidget:FinalizeUnits(...) end
---@param ... any
function __WowWidget:Flush(...) end
--- Formats a number of seconds and returns the resulting string.
---@param seconds? any
---@param abbreviation? any
---@param ... any
---@return string formattedSeconds
function __WowWidget:Format(seconds, abbreviation, ...) end
--- Formats the elapsed duration of this object to a string.
---@param formatter? any
---@param modifier? any
---@param ... any
---@return string formatted
function __WowWidget:FormatElapsedDuration(formatter, modifier, ...) end
---@param number? number
---@param ... any
---@return string formatted
function __WowWidget:FormatNumber(number, ...) end
--- Formats the remaining duration of this object to a string.
---@param formatter? any
---@param modifier? any
---@param ... any
---@return string formatted
function __WowWidget:FormatRemainingDuration(formatter, modifier, ...) end
--- Formats the total duration of this object to a string.
---@param formatter? any
---@param modifier? any
---@param ... any
---@return string formatted
function __WowWidget:FormatTotalDuration(formatter, modifier, ...) end
--- Returns formatted string representing a zero second duration.
---@param abbreviation? any
---@param ... any
---@return string formattedSeconds
function __WowWidget:FormatZero(abbreviation, ...) end
---@param anim? any
---@param variation? number
---@param frame? number
---@param ... any
function __WowWidget:FreezeAnimation(anim, variation, frame, ...) end
---@param ... any
---@return table data
function __WowWidget:GetAbbreviateNumberData(...) end
---@param ... any
---@return any boxBottom
---@return any boxTop
function __WowWidget:GetActiveBoundingBox(...) end
---@param index? number
---@param ... any
function __WowWidget:GetActorAtIndex(index, ...) end
--- Returns all catalog entries being searched (note these are NOT search results, this is the source collection of what's being searched)
---@param ... any
---@return table matchingEntryVariantIDs
function __WowWidget:GetAllSearchItems(...) end
---@param ... any
---@return boolean allowOverlappedModels
function __WowWidget:GetAllowOverlappedModels(...) end
---@param ... any
---@return number alpha
function __WowWidget:GetAlpha(...) end
---@param ... any
---@return any animation
function __WowWidget:GetAnimation(...) end
---@param ... any
---@return any blendOp
function __WowWidget:GetAnimationBlendOperation(...) end
---@param ... any
---@return any groups
function __WowWidget:GetAnimationGroups(...) end
---@param ... any
---@return number variation
function __WowWidget:GetAnimationVariation(...) end
--- Returns the threshold below which numeric values are formatted as approximated strings.
---@param ... any
---@return any approximationSeconds
function __WowWidget:GetApproximationSeconds(...) end
---@param ... any
---@return boolean enabled
function __WowWidget:GetAutoDress(...) end
--- Returns a list of all configured breakpoints on this formatter.
---@param ... any
---@return table breakpoints
function __WowWidget:GetBreakpoints(...) end
---@param ... any
---@return number distance
function __WowWidget:GetCameraDistance(...) end
---@param ... any
---@return number radians
function __WowWidget:GetCameraFacing(...) end
---@param ... any
---@return number farClip
function __WowWidget:GetCameraFarClip(...) end
--- Field of view in radians
---@param ... any
---@return number fov
function __WowWidget:GetCameraFieldOfView(...) end
---@param ... any
---@return number forwardX
---@return number forwardY
---@return number forwardZ
function __WowWidget:GetCameraForward(...) end
---@param ... any
---@return number nearClip
function __WowWidget:GetCameraNearClip(...) end
---@param ... any
---@return number positionX
---@return number positionY
---@return number positionZ
function __WowWidget:GetCameraPosition(...) end
---@param ... any
---@return number rightX
---@return number rightY
---@return number rightZ
function __WowWidget:GetCameraRight(...) end
---@param ... any
---@return number radians
function __WowWidget:GetCameraRoll(...) end
---@param ... any
---@return number targetX
---@return number targetY
---@return number targetZ
function __WowWidget:GetCameraTarget(...) end
---@param ... any
---@return number upX
---@return number upY
---@return number upZ
function __WowWidget:GetCameraUp(...) end
--- Returns the most recent search result entries
---@param ... any
---@return table matchingEntryVariantIDs
function __WowWidget:GetCatalogSearchResults(...) end
---@param ... any
---@return boolean checked
function __WowWidget:GetChecked(...) end
---@param ... any
---@return any texture
function __WowWidget:GetCheckedTexture(...) end
--- Returns the current time of the clock source used by this object.
---@param ... any
---@return any clockTime
function __WowWidget:GetClockTime(...) end
---@param ... any
---@return number alpha
function __WowWidget:GetColorAlpha(...) end
---@param ... any
---@return any texture
function __WowWidget:GetColorAlphaTexture(...) end
---@param ... any
---@return any texture
function __WowWidget:GetColorAlphaThumbTexture(...) end
---@param ... any
---@return number hsvX
---@return number hsvY
---@return number hsvZ
function __WowWidget:GetColorHSV(...) end
---@param ... any
---@return number rgbR
---@return number rgbG
---@return number rgbB
function __WowWidget:GetColorRGB(...) end
---@param ... any
---@return any texture
function __WowWidget:GetColorValueTexture(...) end
---@param ... any
---@return any texture
function __WowWidget:GetColorValueThumbTexture(...) end
---@param ... any
---@return any texture
function __WowWidget:GetColorWheelTexture(...) end
---@param ... any
---@return any texture
function __WowWidget:GetColorWheelThumbTexture(...) end
---@param ... any
---@return any points
function __WowWidget:GetControlPoints(...) end
--- Returns true if the formatter should lowercase all unit format strings.
---@param ... any
---@return boolean convert
function __WowWidget:GetConvertToLower(...) end
--- Returns the base amount of unit health.
---@param ... any
---@return number currentHealth
function __WowWidget:GetCurrentHealth(...) end
--- Returns the percentage of current unit health.
---@param ... any
---@return number currentHealthPercent
function __WowWidget:GetCurrentHealthPercent(...) end
---@param ... any
---@return any curveType
function __WowWidget:GetCurveType(...) end
--- Returns the configured damage absorb clamping mode.
---@param ... any
---@return any damageAbsorbClampMode
function __WowWidget:GetDamageAbsorbClampMode(...) end
--- Calculates damage absorb values and clamping according to the configured options.
---@param ... any
---@return number amount
---@return boolean clamped
function __WowWidget:GetDamageAbsorbs(...) end
--- Returns the default abbreviation mode used for formatting.
---@param ... any
---@return any abbreviation
function __WowWidget:GetDefaultAbbreviation(...) end
---@param ... any
---@return number angle
function __WowWidget:GetDegrees(...) end
---@param ... any
---@return number strength
function __WowWidget:GetDesaturation(...) end
--- Returns the desired unit count for formatting.
---@param ... any
---@return number count
function __WowWidget:GetDesiredUnitCount(...) end
--- Returns the desired unit count curve for formatting.
---@param ... any
---@return any curve
function __WowWidget:GetDesiredUnitCountCurve(...) end
---@param ... any
---@return any texture
function __WowWidget:GetDisabledCheckedTexture(...) end
---@param ... any
---@return number displayID
function __WowWidget:GetDisplayInfo(...) end
---@param ... any
---@return boolean doBlend
function __WowWidget:GetDoBlend(...) end
---@param ... any
---@return any connectionInfo
function __WowWidget:GetDoorConnectionInfo(...) end
---@param ... any
---@return any layer
---@return number sublevel
function __WowWidget:GetDrawLayer(...) end
---@param ... any
---@return any editorModeContext
function __WowWidget:GetEditorModeContext(...) end
--- Calculates the elapsed duration of the stored time span.
---@param modifier? any
---@param ... any
---@return any elapsedDuration
function __WowWidget:GetElapsedDuration(modifier, ...) end
--- Calculates the elapsed duration as a percentage value.
---@param modifier? any
---@param ... any
---@return number elapsedPercent
function __WowWidget:GetElapsedPercent(modifier, ...) end
---@param ... any
---@return any color
function __WowWidget:GetEndColor(...) end
---@param ... any
---@return any relativePoint
---@return any relativeTo
---@return number offsetX
---@return number offsetY
function __WowWidget:GetEndPoint(...) end
--- Calculates the end time of the stored time span.
---@param modifier? any
---@param ... any
---@return any endTime
function __WowWidget:GetEndTime(modifier, ...) end
---@param ... any
---@return number facing
function __WowWidget:GetFacing(...) end
---@param ... any
---@return number fadeDurationSeconds
function __WowWidget:GetFadeDuration(...) end
---@param ... any
---@return number fadePower
function __WowWidget:GetFadePower(...) end
---@param ... any
---@return boolean isFading
function __WowWidget:GetFading(...) end
---@param groupID? number
---@param tagID? number
---@param ... any
---@return boolean active
function __WowWidget:GetFilterTagStatus(groupID, tagID, ...) end
---@param ... any
---@return number categoryID
function __WowWidget:GetFilteredCategoryID(...) end
---@param ... any
---@return number subcategoryID
function __WowWidget:GetFilteredSubcategoryID(...) end
---@param ... any
---@return number columns
function __WowWidget:GetFlipBookColumns(...) end
---@param ... any
---@return number height
function __WowWidget:GetFlipBookFrameHeight(...) end
---@param ... any
---@return number width
function __WowWidget:GetFlipBookFrameWidth(...) end
---@param ... any
---@return number frames
function __WowWidget:GetFlipBookFrames(...) end
---@param ... any
---@return number rows
function __WowWidget:GetFlipBookRows(...) end
---@param ... any
---@return number colorR
---@return number colorG
---@return number colorB
function __WowWidget:GetFogColor(...) end
---@param ... any
---@return number far
function __WowWidget:GetFogFar(...) end
---@param ... any
---@return number near
function __WowWidget:GetFogNear(...) end
---@param ... any
---@return string atlas
function __WowWidget:GetFogOfWarBackgroundAtlas(...) end
---@param ... any
---@return any asset
function __WowWidget:GetFogOfWarBackgroundTexture(...) end
---@param ... any
---@return string atlas
function __WowWidget:GetFogOfWarMaskAtlas(...) end
---@param ... any
---@return any asset
function __WowWidget:GetFogOfWarMaskTexture(...) end
---@param ... any
---@return string fontFile
---@return any height
---@return any flags
function __WowWidget:GetFont(...) end
--- Return is either in uiUnits or internal height due to fixedHeight.
---@param ... any
---@return number height
function __WowWidget:GetFontHeight(...) end
---@param ... any
---@return any font
function __WowWidget:GetFontObject(...) end
---@param alphabet? any
---@param ... any
---@return any font
function __WowWidget:GetFontObjectForAlphabet(alphabet, ...) end
---@param messageID? number
---@param ... any
---@return any fontString
function __WowWidget:GetFontStringByID(messageID, ...) end
---@param ... any
---@return number normalizedAlpha
function __WowWidget:GetFromAlpha(...) end
--- Returns the configured heal absorb clamping mode.
---@param ... any
---@return any healAbsorbClampMode
function __WowWidget:GetHealAbsorbClampMode(...) end
--- Returns the configured heal absorb processing mode.
---@param ... any
---@return any healAbsorbMode
function __WowWidget:GetHealAbsorbMode(...) end
--- Calculates heal absorb values and clamping according to the configured options.
---@param ... any
---@return number amount
---@return boolean clamped
function __WowWidget:GetHealAbsorbs(...) end
---@param ... any
---@return number thickness
function __WowWidget:GetHitRectThickness(...) end
--- Returns the anchor points that determine where the mouse interacts with the nameplate.
---@param ... any
---@return table anchors
function __WowWidget:GetHitTestPoints(...) end
--- Returns the configured incoming heal clamping mode.
---@param ... any
---@return any incomingHealClampMode
function __WowWidget:GetIncomingHealClampMode(...) end
--- Returns the configured incoming heal maximum overflow percentage.
---@param ... any
---@return number incomingHealOverflowPercent
function __WowWidget:GetIncomingHealOverflowPercent(...) end
--- Calculates incoming heal values and clamping according to the configured options.
---@param ... any
---@return number amount
---@return number amountFromHealer
---@return number amountFromOthers
---@return boolean clamped
function __WowWidget:GetIncomingHeals(...) end
---@param ... any
---@return boolean wordWrap
function __WowWidget:GetIndentedWordWrap(...) end
---@param ... any
---@return any mode
function __WowWidget:GetInsertMode(...) end
---@param inventorySlot? number
---@param ... any
---@return any itemTransmogInfo
function __WowWidget:GetItemTransmogInfo(inventorySlot, ...) end
---@param ... any
---@return table infoList
function __WowWidget:GetItemTransmogInfoList(...) end
---@param ... any
---@return any justifyH
function __WowWidget:GetJustifyH(...) end
---@param ... any
---@return any justifyV
function __WowWidget:GetJustifyV(...) end
---@param ... any
---@return boolean keepModelOnHide
function __WowWidget:GetKeepModelOnHide(...) end
---@param ... any
---@return boolean enabled
---@return any light
function __WowWidget:GetLight(...) end
---@param ... any
---@return number colorR
---@return number colorG
---@return number colorB
function __WowWidget:GetLightAmbientColor(...) end
---@param ... any
---@return number colorR
---@return number colorG
---@return number colorB
function __WowWidget:GetLightDiffuseColor(...) end
---@param ... any
---@return number directionX
---@return number directionY
---@return number directionZ
function __WowWidget:GetLightDirection(...) end
---@param ... any
---@return number positionX
---@return number positionY
---@return number positionZ
function __WowWidget:GetLightPosition(...) end
---@param ... any
---@return any lightType
function __WowWidget:GetLightType(...) end
---@param ... any
---@return number file
function __WowWidget:GetLowerBackgroundFileName(...) end
---@param ... any
---@return number file
function __WowWidget:GetLowerBorderFile(...) end
---@param ... any
---@return number file
function __WowWidget:GetLowerEmblemFile(...) end
---@param texture? any
---@param ... any
function __WowWidget:GetLowerEmblemTexture(texture, ...) end
---@param ... any
---@return number uiMapID
function __WowWidget:GetMapID(...) end
---@param ... any
---@return number scalar
function __WowWidget:GetMaskScalar(...) end
---@param ... any
---@return any boxBottom
---@return any boxTop
function __WowWidget:GetMaxBoundingBox(...) end
---@param ... any
---@return number maxCharacterSlotCount
function __WowWidget:GetMaxCharacterSlotCount(...) end
---@param ... any
---@return number maxOrder
function __WowWidget:GetMaxControlPointOrder(...) end
--- Returns the maximum interval band permitted for formatting.
---@param ... any
---@return any interval
function __WowWidget:GetMaxInterval(...) end
--- Returns the maximum interval band curve permitted for formatting.
---@param ... any
---@return any curve
function __WowWidget:GetMaxIntervalCurve(...) end
---@param ... any
---@return number maxSnapshots
function __WowWidget:GetMaxSnapshots(...) end
--- Returns the maximum clamping amount for damage absorbs.
---@param ... any
---@return number maximumDamageAbsorbs
function __WowWidget:GetMaximumDamageAbsorbs(...) end
--- Returns the maximum clamping amount for heal absorbs.
---@param ... any
---@return number maximumHealAbsorbs
function __WowWidget:GetMaximumHealAbsorbs(...) end
--- Returns the base amount of maximum unit health.
---@param ... any
---@return number maximumHealth
function __WowWidget:GetMaximumHealth(...) end
--- Returns the configured maximum health mode.
---@param ... any
---@return any maximumHealthMode
function __WowWidget:GetMaximumHealthMode(...) end
--- Returns the maximum clamping amount for incoming heals.
---@param ... any
---@return number maximumIncomingHeals
function __WowWidget:GetMaximumIncomingHeals(...) end
--- Returns the threshold below which a value will be formatted as a decimal number of seconds with one place for milliseconds (eg. '3.4')
---@param ... any
---@return any threshold
function __WowWidget:GetMillisecondsThreshold(...) end
--- Returns the minimum interval band permitted for formatting.
---@param ... any
---@return any interval
function __WowWidget:GetMinInterval(...) end
--- Returns the minimum interval band curve permitted for formatting.
---@param ... any
---@return any curve
function __WowWidget:GetMinIntervalCurve(...) end
---@param ... any
---@return number minValue
---@return number maxValue
function __WowWidget:GetMinMaxValues(...) end
--- Returns the base amount of missing unit health.
---@param ... any
---@return number missingHealth
function __WowWidget:GetMissingHealth(...) end
--- Returns the percentage of missing unit health.
---@param ... any
---@return number missingHealthPercent
function __WowWidget:GetMissingHealthPercent(...) end
--- Returns the divisor used to convert a duration from real time to base time.
---@param ... any
---@return number modRate
function __WowWidget:GetModRate(...) end
---@param ... any
---@return number alpha
function __WowWidget:GetModelAlpha(...) end
---@param ... any
---@return any layer
---@return number sublayer
function __WowWidget:GetModelDrawLayer(...) end
---@param ... any
---@return number file
function __WowWidget:GetModelFileID(...) end
---@param ... any
---@return string path
function __WowWidget:GetModelPath(...) end
---@param ... any
---@return number scale
function __WowWidget:GetModelScale(...) end
---@param ... any
---@return string guid
function __WowWidget:GetModelUnitGUID(...) end
---@param ... any
---@return any units
function __WowWidget:GetMouseOverUnits(...) end
---@param ... any
---@return number numActors
function __WowWidget:GetNumActors(...) end
---@param ... any
---@return number numPoints
function __WowWidget:GetNumPoints(...) end
--- Returns the total number of entries being searched through
---@param ... any
---@return number numSearchItems
function __WowWidget:GetNumSearchItems(...) end
---@param ... any
---@return number numObjectives
function __WowWidget:GetNumTooltips(...) end
---@param ... any
---@return boolean enabled
function __WowWidget:GetObeyHideInTransmogFlag(...) end
---@param ... any
---@return boolean isObeyStepOnDrag
function __WowWidget:GetObeyStepOnDrag(...) end
---@param ... any
---@return number offsetU
---@return number offsetV
function __WowWidget:GetOffset(...) end
---@param ... any
---@return number order
function __WowWidget:GetOrder(...) end
---@param ... any
---@return any orientation
function __WowWidget:GetOrientation(...) end
---@param ... any
---@return any point
---@return number originX
---@return number originY
function __WowWidget:GetOrigin(...) end
---@param ... any
---@return number scale
function __WowWidget:GetParticleOverrideScale(...) end
---@param ... any
---@return boolean paused
---@return boolean globalPaused
function __WowWidget:GetPaused(...) end
---@param ... any
---@return any type
function __WowWidget:GetPinType(...) end
---@param ... any
---@return number positionX
---@return number positionY
function __WowWidget:GetPingPosition(...) end
---@param ... any
---@return number pitch
function __WowWidget:GetPitch(...) end
---@param ... any
---@return number scale
function __WowWidget:GetPlayerPingScale(...) end
--- Returns the vector for an individual point index on the curve.
---@param index? number
---@param ... any
---@return any point
function __WowWidget:GetPoint(index, ...) end
---@param point? any
---@param resolveCollapsed? boolean
---@param ... any
---@return any point
---@return any relativeTo
---@return any relativePoint
---@return number offsetX
---@return number offsetY
function __WowWidget:GetPointByName(point, resolveCollapsed, ...) end
--- Returns the total number of points on the curve.
---@param ... any
---@return any count
function __WowWidget:GetPointCount(...) end
--- Returns the vectors for all points on the curve.
---@param ... any
---@return table point
function __WowWidget:GetPoints(...) end
---@param ... any
---@return number positionX
---@return number positionY
---@return number positionZ
function __WowWidget:GetPosition(...) end
--- Returns the raw total figures used for data calculations.
---@param ... any
---@return any predictedValues
function __WowWidget:GetPredictedValues(...) end
---@param ... any
---@return number angle
function __WowWidget:GetRadians(...) end
--- Calculates the remaining duration of the stored time span.
---@param modifier? any
---@param ... any
---@return any remainingDuration
function __WowWidget:GetRemainingDuration(modifier, ...) end
--- Calculates the remaining duration as a percentage value.
---@param modifier? any
---@param ... any
---@return number remainingPercent
function __WowWidget:GetRemainingPercent(modifier, ...) end
---@param ... any
---@return number roll
function __WowWidget:GetRoll(...) end
---@param ... any
---@return string roomGUID
function __WowWidget:GetRoomGUID(...) end
---@param ... any
---@return string name
function __WowWidget:GetRoomName(...) end
---@param ... any
---@return number scale
function __WowWidget:GetScale(...) end
---@param ... any
---@return number scaleX
---@return number scaleY
function __WowWidget:GetScaleFrom(...) end
---@param ... any
---@return number scaleX
---@return number scaleY
function __WowWidget:GetScaleTo(...) end
---@param ... any
---@return string tooltipText
function __WowWidget:GetScenarioTooltipText(...) end
--- Returns the total number of owned instances across all most recent search result entries
---@param ... any
---@return number searchCount
function __WowWidget:GetSearchCount(...) end
---@param ... any
---@return string searchText
function __WowWidget:GetSearchText(...) end
---@param ... any
---@return number colorR
---@return number colorG
---@return number colorB
---@return number colorA
function __WowWidget:GetShadowColor(...) end
---@param ... any
---@return number strength
function __WowWidget:GetShadowEffect(...) end
---@param ... any
---@return number offsetX
---@return number offsetY
function __WowWidget:GetShadowOffset(...) end
---@param ... any
---@return boolean sheathed
function __WowWidget:GetSheathed(...) end
---@param ... any
---@return any sortType
function __WowWidget:GetSortType(...) end
---@param ... any
---@return number spacing
function __WowWidget:GetSpacing(...) end
---@param ... any
---@return number spellVisualKitID
function __WowWidget:GetSpellVisualKit(...) end
---@param ... any
---@return any color
function __WowWidget:GetStartColor(...) end
---@param ... any
---@return any relativePoint
---@return any relativeTo
---@return number offsetX
---@return number offsetY
function __WowWidget:GetStartPoint(...) end
--- Calculates the start time of the stored time span.
---@param modifier? any
---@param ... any
---@return any startTime
function __WowWidget:GetStartTime(modifier, ...) end
---@param ... any
---@return number stepsPerPage
function __WowWidget:GetStepsPerPage(...) end
--- Returns the whitespace stripping mode of the formatter.
---@param ... any
---@return any strip
function __WowWidget:GetStripIntervalWhitespace(...) end
---@param ... any
---@return number colorR
---@return number colorG
---@return number colorB
---@return number colorA
function __WowWidget:GetTextColor(...) end
---@param ... any
---@return number thickness
function __WowWidget:GetThickness(...) end
---@param ... any
---@return any texture
function __WowWidget:GetThumbTexture(...) end
---@param ... any
---@return number timeVisibleSeconds
function __WowWidget:GetTimeVisible(...) end
---@param ... any
---@return number normalizedAlpha
function __WowWidget:GetToAlpha(...) end
---@param index? number
---@param ... any
---@return number objectiveIndex
function __WowWidget:GetTooltipIndex(index, ...) end
--- Returns the base total amount of all applied damage absorb shields.
---@param ... any
---@return number totalDamageAbsorbs
function __WowWidget:GetTotalDamageAbsorbs(...) end
--- Calculates the total duration of the stored time span.
---@param modifier? any
---@param ... any
---@return any totalDuration
function __WowWidget:GetTotalDuration(modifier, ...) end
--- Returns the base total amount of all applied heal absorption effects.
---@param ... any
---@return number totalHealAbsorbs
function __WowWidget:GetTotalHealAbsorbs(...) end
--- Returns the base total amount of all incoming heals.
---@param ... any
---@return number totalIncomingHeals
function __WowWidget:GetTotalIncomingHeals(...) end
--- Returns the base total amount of all incoming heals from the healer unit, if any.
---@param ... any
---@return number totalIncomingHealsFromHealer
function __WowWidget:GetTotalIncomingHealsFromHealer(...) end
--- Returns the configured type of the curve.
---@param ... any
---@return any curveType
function __WowWidget:GetType(...) end
---@param ... any
---@return number uiMapID
function __WowWidget:GetUiMapID(...) end
---@param ... any
---@return number file
function __WowWidget:GetUpperBackgroundFileName(...) end
---@param ... any
---@return number file
function __WowWidget:GetUpperBorderFile(...) end
---@param ... any
---@return number file
function __WowWidget:GetUpperEmblemFile(...) end
---@param texture? any
---@param ... any
function __WowWidget:GetUpperEmblemTexture(texture, ...) end
---@param ... any
---@return boolean enabled
function __WowWidget:GetUseTransmogChoices(...) end
---@param ... any
---@return boolean enabled
function __WowWidget:GetUseTransmogSkin(...) end
---@param ... any
---@return number value
function __WowWidget:GetValue(...) end
---@param ... any
---@return number valueStep
function __WowWidget:GetValueStep(...) end
---@param ... any
---@return any insets
function __WowWidget:GetViewInsets(...) end
---@param ... any
---@return number translationX
---@return number translationY
function __WowWidget:GetViewTranslation(...) end
---@param ... any
---@return number worldScale
function __WowWidget:GetWorldScale(...) end
---@param ... any
---@return number yaw
function __WowWidget:GetYaw(...) end
---@param ... any
---@return number zoomFactor
function __WowWidget:GetZoom(...) end
---@param ... any
---@return number zoomLevels
function __WowWidget:GetZoomLevels(...) end
---@param anim? any
---@param ... any
---@return boolean hasAnimation
function __WowWidget:HasAnimation(anim, ...) end
---@param ... any
---@return boolean hasAttachedFixture
function __WowWidget:HasAttachedFixture(...) end
---@param ... any
---@return boolean hasAttachmentPoints
function __WowWidget:HasAttachmentPoints(...) end
---@param ... any
---@return boolean hasCustomCamera
function __WowWidget:HasCustomCamera(...) end
---@param messageID? number
---@param ... any
---@return boolean hasMessage
function __WowWidget:HasMessageByID(messageID, ...) end
--- Returns true if the curve has been configured with any secret values. Curves with secret values always produce secret results when evaluated.
---@param ... any
---@return boolean hasSecretValues
function __WowWidget:HasSecretValues(...) end
---@param ... any
function __WowWidget:Hide(...) end
---@param scaleFactor? number
---@param ... any
function __WowWidget:InitializeCamera(scaleFactor, ...) end
---@param scaleFactor? number
---@param ... any
function __WowWidget:InitializePanCamera(scaleFactor, ...) end
---@param ... any
function __WowWidget:InitializeTabardColors(...) end
---@param ... any
---@return boolean isActive
function __WowWidget:IsAllowedIndoorsActive(...) end
---@param ... any
---@return boolean isActive
function __WowWidget:IsAllowedOutdoorsActive(...) end
--- Returns true if this pin's associated room, or anything attached to it, is selected. Ex: If pin is for a door, returns true if its room, or any other doors on that room, are selected
---@param ... any
---@return boolean isSelected
function __WowWidget:IsAnyPartOfRoomSelected(...) end
---@param ... any
---@return boolean isActive
function __WowWidget:IsBaseVariantOnlyActive(...) end
---@param ... any
---@return boolean isActive
function __WowWidget:IsCollectedActive(...) end
---@param ... any
---@return boolean isActive
function __WowWidget:IsCustomizableOnlyActive(...) end
---@param ... any
---@return boolean isDraggingThumb
function __WowWidget:IsDraggingThumb(...) end
---@param ... any
---@return boolean enabled
function __WowWidget:IsEnabled(...) end
---@param ... any
---@return boolean isActive
function __WowWidget:IsFirstAcquisitionBonusOnlyActive(...) end
---@param ... any
---@return boolean ready
function __WowWidget:IsGeoReady(...) end
---@param ... any
---@return boolean isGuildTabard
function __WowWidget:IsGuildTabard(...) end
---@param ... any
---@return boolean isVisible
function __WowWidget:IsLightVisible(...) end
---@param ... any
---@return boolean isLoaded
function __WowWidget:IsLoaded(...) end
--- Will be nil if pin is not a Door
---@param ... any
---@return boolean isOccupied
function __WowWidget:IsOccupiedDoor(...) end
---@param ... any
---@return boolean preferringCollisionBounds
function __WowWidget:IsPreferringModelCollisionBounds(...) end
---@param ... any
---@return boolean isSearchInProgress
function __WowWidget:IsSearchInProgress(...) end
---@param ... any
---@return boolean isSelected
function __WowWidget:IsSelected(...) end
---@param ... any
---@return boolean isShown
function __WowWidget:IsShown(...) end
---@param slot? number
---@param ... any
---@return boolean allowed
function __WowWidget:IsSlotAllowed(slot, ...) end
---@param slot? number
---@param ... any
---@return boolean visible
function __WowWidget:IsSlotVisible(slot, ...) end
---@param snapshotID? number
---@param ... any
---@return boolean isValid
function __WowWidget:IsSnapshotValid(snapshotID, ...) end
---@param ... any
---@return boolean isActive
function __WowWidget:IsStoredOnlyActive(...) end
---@param ... any
---@return boolean isActive
function __WowWidget:IsUncollectedActive(...) end
---@param ... any
---@return boolean x
---@return boolean y
---@return boolean z
function __WowWidget:IsUsingCenterForOrigin(...) end
---@param ... any
---@return boolean useCenter
function __WowWidget:IsUsingModelCenterToTransform(...) end
---@param ... any
---@return boolean isValid
function __WowWidget:IsValid(...) end
---@param ... any
---@return boolean isValid
function __WowWidget:IsValidForSelectedFloorplan(...) end
---@param ... any
---@return boolean isVisible
function __WowWidget:IsVisible(...) end
--- Returns true if the duration object is measuring a zero duration time span.
---@param ... any
---@return boolean isZero
function __WowWidget:IsZero(...) end
---@param ... any
function __WowWidget:MakeCurrentCameraCustom(...) end
---@param ... any
function __WowWidget:NavigateBack(...) end
---@param ... any
function __WowWidget:NavigateForward(...) end
---@param urlType? string
---@param ... any
function __WowWidget:NavigateHome(urlType, ...) end
---@param ... any
function __WowWidget:NavigateReload(...) end
---@param ... any
function __WowWidget:NavigateStop(...) end
---@param checkoutID? number
---@param ... any
---@return boolean wasOpened
function __WowWidget:OpenCheckout(checkoutID, ...) end
---@param ... any
function __WowWidget:OpenExternalLink(...) end
---@param index? number
---@param ... any
function __WowWidget:OpenTicket(index, ...) end
---@param locationX? number
---@param locationY? number
---@param ... any
function __WowWidget:PingLocation(locationX, locationY, ...) end
---@param animKit? number
---@param loop? boolean
---@param ... any
function __WowWidget:PlayAnimKit(animKit, loop, ...) end
---@param animationKit? number
---@param isLooping? boolean
---@param ... any
function __WowWidget:PlayAnimationKit(animationKit, isLooping, ...) end
---@param pointX? number
---@param pointY? number
---@param pointZ? number
---@param ... any
---@return number point2DX
---@return number point2DY
---@return number depth
function __WowWidget:Project3DPointTo2D(pointX, pointY, pointZ, ...) end
---@param ... any
function __WowWidget:RefreshCamera(...) end
---@param ... any
function __WowWidget:RefreshUnit(...) end
---@param ... any
---@return boolean success
function __WowWidget:ReleaseFrontEndCharacterDisplays(...) end
--- Removes a single point from the curve. Raises an error if the supplied point index is out of range.
---@param index? number
---@param ... any
function __WowWidget:RemovePoint(index, ...) end
---@param asset? any
---@param ... any
function __WowWidget:ReplaceIconTexture(asset, ...) end
--- Resets the duration object to represent a zero duration time span.
---@param ... any
function __WowWidget:Reset(...) end
--- Removes all configured breakpoints from the formatter and replaces them with appropriate defaults for the client locale.
---@param ... any
function __WowWidget:ResetBreakpoints(...) end
---@param ... any
function __WowWidget:ResetLights(...) end
---@param messageID? number
---@param ... any
function __WowWidget:ResetMessageFadeByID(messageID, ...) end
---@param ... any
function __WowWidget:ResetNextHandSlot(...) end
--- Resets all stored healing values used for calculations.
---@param ... any
function __WowWidget:ResetPredictedValues(...) end
--- Run search with all current param values
---@param ... any
function __WowWidget:RunSearch(...) end
---@param ... any
function __WowWidget:Save(...) end
---@param ... any
function __WowWidget:Select(...) end
---@param data? table
---@param ... any
function __WowWidget:SetAbbreviateNumberData(data, ...) end
--- Sets the anchor points that determine where the mouse interacts with the nameplate to fully encompass the target region.
---@param relativeTo? any
---@param ... any
function __WowWidget:SetAllHitTestPoints(relativeTo, ...) end
--- Set the toggle state of all filter tags within a specific group; If active, only entries that match Any of the tags in the group will be included in search results
---@param groupID? number
---@param active? boolean
---@param ... any
function __WowWidget:SetAllInFilterTagGroup(groupID, active, ...) end
---@param relativeTo? any
---@param doResize? boolean
---@param ... any
function __WowWidget:SetAllPoints(relativeTo, doResize, ...) end
---@param allowOverlappedModels? boolean
---@param ... any
function __WowWidget:SetAllowOverlappedModels(allowOverlappedModels, ...) end
--- Search parameter; If true, entries that can be placed in house interiors will be included in the search; Note many decor objects can be placed both indoors and outdoors, so having only this toggled on may still include decor that can also be placed outdoors
---@param isActive? boolean
---@param ... any
function __WowWidget:SetAllowedIndoors(isActive, ...) end
--- Search parameter; If true, entries that can be placed outside in plots will be included in the search; Note many decor objects can be placed both indoors and outdoors, so having only this toggled on may still include decor that can also be placed indoors
---@param isActive? boolean
---@param ... any
function __WowWidget:SetAllowedOutdoors(isActive, ...) end
---@param alpha? number
---@param ... any
function __WowWidget:SetAlpha(alpha, ...) end
---@param offset? number
---@param ... any
function __WowWidget:SetAnimOffset(offset, ...) end
---@param anim? any
---@param variation? number
---@param ... any
function __WowWidget:SetAnimation(anim, variation, ...) end
---@param blendOp? any
---@param ... any
function __WowWidget:SetAnimationBlendOperation(blendOp, ...) end
--- Configures the formatter to render numeric values between zero and this value as approximated strings (eg. '< 1m').
---@param seconds? any
---@param ... any
function __WowWidget:SetApproximationSeconds(seconds, ...) end
---@param alpha? number
---@param ... any
function __WowWidget:SetArchBlobInsideAlpha(alpha, ...) end
---@param asset? any
---@param ... any
function __WowWidget:SetArchBlobInsideTexture(asset, ...) end
---@param alpha? number
---@param ... any
function __WowWidget:SetArchBlobOutsideAlpha(alpha, ...) end
---@param asset? any
---@param ... any
function __WowWidget:SetArchBlobOutsideTexture(asset, ...) end
---@param alpha? number
---@param ... any
function __WowWidget:SetArchBlobRingAlpha(alpha, ...) end
---@param scalar? number
---@param ... any
function __WowWidget:SetArchBlobRingScalar(scalar, ...) end
---@param asset? any
---@param ... any
function __WowWidget:SetArchBlobRingTexture(asset, ...) end
---@param enabled? boolean
---@param ... any
function __WowWidget:SetAutoDress(enabled, ...) end
--- If true, searcher automatically updates results whenever search param values are changed
---@param autoUpdateActive? boolean
---@param ... any
function __WowWidget:SetAutoUpdateOnParamChanges(autoUpdateActive, ...) end
---@param ... any
function __WowWidget:SetBarberShopAlternateForm(...) end
--- Search parameter; If true, only the base variant of each decor entry will be included
---@param isActive? boolean
---@param ... any
function __WowWidget:SetBaseVariantOnly(isActive, ...) end
---@param asset? any
---@param ... any
function __WowWidget:SetBlipTexture(asset, ...) end
---@param alpha? number
---@param ... any
function __WowWidget:SetBorderAlpha(alpha, ...) end
---@param scalar? number
---@param ... any
function __WowWidget:SetBorderScalar(scalar, ...) end
---@param asset? any
---@param ... any
function __WowWidget:SetBorderTexture(asset, ...) end
--- Replaces all breakpoints on the formatter.
---@param breakpoints? table
---@param ... any
function __WowWidget:SetBreakpoints(breakpoints, ...) end
---@param scale? number
---@param ... any
function __WowWidget:SetCamDistanceScale(scale, ...) end
---@param cameraIndex? number
---@param ... any
function __WowWidget:SetCamera(cameraIndex, ...) end
---@param distance? number
---@param ... any
function __WowWidget:SetCameraDistance(distance, ...) end
---@param radians? number
---@param ... any
function __WowWidget:SetCameraFacing(radians, ...) end
---@param farClip? number
---@param ... any
function __WowWidget:SetCameraFarClip(farClip, ...) end
--- Field of view in radians
---@param fov? number
---@param ... any
function __WowWidget:SetCameraFieldOfView(fov, ...) end
---@param nearClip? number
---@param ... any
function __WowWidget:SetCameraNearClip(nearClip, ...) end
---@param forwardX? number
---@param forwardY? number
---@param forwardZ? number
---@param rightX? number
---@param rightY? number
---@param rightZ? number
---@param upX? number
---@param upY? number
---@param upZ? number
---@param ... any
function __WowWidget:SetCameraOrientationByAxisVectors(forwardX, forwardY, forwardZ, rightX, rightY, rightZ, upX, upY, upZ, ...) end
---@param yaw? number
---@param pitch? number
---@param roll? number
---@param ... any
function __WowWidget:SetCameraOrientationByYawPitchRoll(yaw, pitch, roll, ...) end
---@param positionX? number
---@param positionY? number
---@param positionZ? number
---@param ... any
function __WowWidget:SetCameraPosition(positionX, positionY, positionZ, ...) end
---@param radians? number
---@param ... any
function __WowWidget:SetCameraRoll(radians, ...) end
---@param positionX? number
---@param positionY? number
---@param positionZ? number
---@param ... any
function __WowWidget:SetCameraTarget(positionX, positionY, positionZ, ...) end
--- Configures the formatter to promote intervals if values are large enough (eg. '60m' -> '1h').
---@param canRound? boolean
---@param ... any
function __WowWidget:SetCanRoundUpIntervals(canRound, ...) end
--- Configures the formatter to round the last formatted unit up, rather than down.
---@param canRound? boolean
---@param ... any
function __WowWidget:SetCanRoundUpLastUnit(canRound, ...) end
---@param checked? boolean
---@param ... any
function __WowWidget:SetChecked(checked, ...) end
---@param asset? any
---@param ... any
function __WowWidget:SetCheckedTexture(asset, ...) end
--- Search parameter; If true, includes all owned entries, including those that are in storage OR placed in an owned house or plot; See IsStoredOnlyActive for a more exclusive toggle
---@param isActive? boolean
---@param ... any
function __WowWidget:SetCollected(isActive, ...) end
---@param alpha? number
---@param ... any
function __WowWidget:SetColorAlpha(alpha, ...) end
---@param texture? any
---@param ... any
function __WowWidget:SetColorAlphaTexture(texture, ...) end
---@param texture? any
---@param ... any
function __WowWidget:SetColorAlphaThumbTexture(texture, ...) end
---@param hsvX? number
---@param hsvY? number
---@param hsvZ? number
---@param ... any
function __WowWidget:SetColorHSV(hsvX, hsvY, hsvZ, ...) end
---@param rgbR? number
---@param rgbG? number
---@param rgbB? number
---@param ... any
function __WowWidget:SetColorRGB(rgbR, rgbG, rgbB, ...) end
---@param texture? any
---@param ... any
function __WowWidget:SetColorValueTexture(texture, ...) end
---@param texture? any
---@param ... any
function __WowWidget:SetColorValueThumbTexture(texture, ...) end
---@param texture? any
---@param ... any
function __WowWidget:SetColorWheelTexture(texture, ...) end
---@param texture? any
---@param ... any
function __WowWidget:SetColorWheelThumbTexture(texture, ...) end
--- Configures the formatter to convert all interval format strings to lowercase.
---@param convert? boolean
---@param ... any
function __WowWidget:SetConvertToLower(convert, ...) end
---@param asset? any
---@param ... any
function __WowWidget:SetCorpsePOIArrowTexture(asset, ...) end
---@param creatureID? number
---@param displayID? number
---@param ... any
function __WowWidget:SetCreature(creatureID, displayID, ...) end
---@param creatureID? number
---@param ... any
function __WowWidget:SetCreatureData(creatureID, ...) end
---@param curveType? any
---@param ... any
function __WowWidget:SetCurveType(curveType, ...) end
---@param cameraIndex? number
---@param ... any
function __WowWidget:SetCustomCamera(cameraIndex, ...) end
--- Search parameter; If true, catalog entries that cannot be customized (ie dyed) will be excluded from the search
---@param isActive? boolean
---@param ... any
function __WowWidget:SetCustomizableOnly(isActive, ...) end
--- Changes the clamping mode used when calculating damage absorb amounts.
---@param damageAbsorbClampMode? any
---@param ... any
function __WowWidget:SetDamageAbsorbClampMode(damageAbsorbClampMode, ...) end
--- Sets the default abbreviation mode used for formatting.
---@param abbreviation? any
---@param ... any
function __WowWidget:SetDefaultAbbreviation(abbreviation, ...) end
---@param angle? number
---@param ... any
function __WowWidget:SetDegrees(angle, ...) end
---@param strength? number
---@param ... any
function __WowWidget:SetDesaturation(strength, ...) end
--- Sets the desired unit count used for formatting.
---@param count? number
---@param ... any
function __WowWidget:SetDesiredUnitCount(count, ...) end
--- Sets the desired unit count used for formatting to a curve that will be evaluated with seconds values to produce a desired unit count.
---@param curve? any
---@param ... any
function __WowWidget:SetDesiredUnitCountCurve(curve, ...) end
---@param asset? any
---@param ... any
function __WowWidget:SetDisabledCheckedTexture(asset, ...) end
---@param displayID? number
---@param mountDisplayID? number
---@param ... any
function __WowWidget:SetDisplayInfo(displayID, mountDisplayID, ...) end
---@param doBlend? boolean
---@param ... any
function __WowWidget:SetDoBlend(doBlend, ...) end
---@param layer? any
---@param ... any
function __WowWidget:SetDrawLayer(layer, ...) end
--- Search parameter; If set, limits search results to only entries that are used/valid in the specified editor mode
---@param editorModeContext? any
---@param ... any
function __WowWidget:SetEditorModeContext(editorModeContext, ...) end
---@param enabled? boolean
---@param ... any
function __WowWidget:SetEnabled(enabled, ...) end
---@param color? any
---@param ... any
function __WowWidget:SetEndColor(color, ...) end
---@param relativePoint? any
---@param relativeTo? any
---@param offsetX? number
---@param offsetY? number
---@param ... any
function __WowWidget:SetEndPoint(relativePoint, relativeTo, offsetX, offsetY, ...) end
---@param facing? number
---@param ... any
function __WowWidget:SetFacing(facing, ...) end
---@param isFacingLeft? boolean
---@param ... any
function __WowWidget:SetFacingLeft(isFacingLeft, ...) end
---@param fadeDurationSeconds? number
---@param ... any
function __WowWidget:SetFadeDuration(fadeDurationSeconds, ...) end
---@param fadePower? number
---@param ... any
function __WowWidget:SetFadePower(fadePower, ...) end
---@param fadeInSeconds? number
---@param fadeOutSeconds? number
---@param ... any
function __WowWidget:SetFadeTimes(fadeInSeconds, fadeOutSeconds, ...) end
---@param fading? boolean
---@param ... any
function __WowWidget:SetFading(fading, ...) end
---@param alpha? number
---@param ... any
function __WowWidget:SetFillAlpha(alpha, ...) end
---@param asset? any
---@param ... any
function __WowWidget:SetFillTexture(asset, ...) end
--- Set the toggle state of a single filter tag within a specific group
---@param groupID? number
---@param tagID? number
---@param active? boolean
---@param ... any
function __WowWidget:SetFilterTagStatus(groupID, tagID, active, ...) end
--- Search parameter; If set, limits search results to only those within the specified category
---@param categoryID? number
---@param ... any
function __WowWidget:SetFilteredCategoryID(categoryID, ...) end
--- Search parameter; If set, limits search results to only those within the specified subcategory
---@param subcategoryID? number
---@param ... any
function __WowWidget:SetFilteredSubcategoryID(subcategoryID, ...) end
--- Search parameter; If true, excludes any entries that do not reward house xp when acquired for the first time
---@param isActive? boolean
---@param ... any
function __WowWidget:SetFirstAcquisitionBonusOnly(isActive, ...) end
---@param columns? number
---@param ... any
function __WowWidget:SetFlipBookColumns(columns, ...) end
---@param height? number
---@param ... any
function __WowWidget:SetFlipBookFrameHeight(height, ...) end
---@param width? number
---@param ... any
function __WowWidget:SetFlipBookFrameWidth(width, ...) end
---@param frames? number
---@param ... any
function __WowWidget:SetFlipBookFrames(frames, ...) end
---@param rows? number
---@param ... any
function __WowWidget:SetFlipBookRows(rows, ...) end
---@param ... any
function __WowWidget:SetFocus(...) end
---@param colorR? number
---@param colorG? number
---@param colorB? number
---@param ... any
function __WowWidget:SetFogColor(colorR, colorG, colorB, ...) end
---@param far? number
---@param ... any
function __WowWidget:SetFogFar(far, ...) end
---@param near? number
---@param ... any
function __WowWidget:SetFogNear(near, ...) end
---@param atlas? string
---@param ... any
function __WowWidget:SetFogOfWarBackgroundAtlas(atlas, ...) end
---@param asset? any
---@param horizontalTile? boolean
---@param verticalTile? boolean
---@param ... any
function __WowWidget:SetFogOfWarBackgroundTexture(asset, horizontalTile, verticalTile, ...) end
---@param atlas? string
---@param ... any
function __WowWidget:SetFogOfWarMaskAtlas(atlas, ...) end
---@param asset? any
---@param ... any
function __WowWidget:SetFogOfWarMaskTexture(asset, ...) end
---@param fontFile? string
---@param height? any
---@param flags? any
---@param ... any
function __WowWidget:SetFont(fontFile, height, flags, ...) end
--- Preserves all flags, does correct height conversion due to fixedHeight.
---@param height? number
---@param ... any
function __WowWidget:SetFontHeight(height, ...) end
---@param font? any
---@param ... any
function __WowWidget:SetFontObject(font, ...) end
---@param normalizedAlpha? number
---@param ... any
function __WowWidget:SetFromAlpha(normalizedAlpha, ...) end
---@param characterIndex? number
---@param ... any
---@return boolean success
function __WowWidget:SetFrontEndLobbyModelFromDefaultCharacterDisplay(characterIndex, ...) end
---@param glow? number
---@param ... any
function __WowWidget:SetGlow(glow, ...) end
---@param gradientIndex0? number
---@param gradientIndex1? number
---@param gradientIndex2? number
---@param gradientIndex3? number
---@param ... any
function __WowWidget:SetGradientMask(gradientIndex0, gradientIndex1, gradientIndex2, gradientIndex3, ...) end
---@param grad0DyeColorID? number
---@param grad1DyeColorID? number
---@param grad2DyeColorID? number
---@param ... any
function __WowWidget:SetGradientMaskWithDyes(grad0DyeColorID, grad1DyeColorID, grad2DyeColorID, ...) end
--- Changes the clamping mode used when calculating heal absorb amounts.
---@param healAbsorbClampMode? any
---@param ... any
function __WowWidget:SetHealAbsorbClampMode(healAbsorbClampMode, ...) end
--- Changes the processing mode used when calculating both heal absorb and incoming heal amounts.
---@param healAbsorbMode? any
---@param ... any
function __WowWidget:SetHealAbsorbMode(healAbsorbMode, ...) end
---@param height? number
---@param ... any
function __WowWidget:SetHeight(height, ...) end
---@param factor? number
---@param ... any
function __WowWidget:SetHeightFactor(factor, ...) end
---@param thickness? number
---@param ... any
function __WowWidget:SetHitRectThickness(thickness, ...) end
--- Sets the anchor points that determine where the mouse interacts with the nameplate.
---@param anchors? table
---@param ... any
function __WowWidget:SetHitTestPoints(anchors, ...) end
---@param asset? any
---@param ... any
function __WowWidget:SetIconTexture(asset, ...) end
--- Changes the clamping mode used when calculating incoming heal amounts.
---@param incomingHealClampMode? any
---@param ... any
function __WowWidget:SetIncomingHealClampMode(incomingHealClampMode, ...) end
--- Changes the maximum overflow percentage for incoming heals. Increasing this to a value over 1.0 will mean that incoming heals can extend beyond maximum health.
---@param incomingHealOverflowPercent? number
---@param ... any
function __WowWidget:SetIncomingHealOverflowPercent(incomingHealOverflowPercent, ...) end
---@param wordWrap? boolean
---@param ... any
function __WowWidget:SetIndentedWordWrap(wordWrap, ...) end
---@param mode? any
---@param ... any
function __WowWidget:SetInsertMode(mode, ...) end
---@param itemID? number
---@param appearanceModID? number
---@param itemVisualID? number
---@param ... any
function __WowWidget:SetItem(itemID, appearanceModID, itemVisualID, ...) end
---@param itemAppearanceID? number
---@param itemVisualID? number
---@param itemSubclass? any
---@param ... any
function __WowWidget:SetItemAppearance(itemAppearanceID, itemVisualID, itemSubclass, ...) end
---@param itemTransmogInfo? any
---@param inventorySlot? number
---@param ignoreChildItems? boolean
---@param ... any
---@return any result
function __WowWidget:SetItemTransmogInfo(itemTransmogInfo, inventorySlot, ignoreChildItems, ...) end
---@param jumpLength? number
---@param jumpHeight? number
---@param ... any
function __WowWidget:SetJumpInfo(jumpLength, jumpHeight, ...) end
---@param justifyH? any
---@param ... any
function __WowWidget:SetJustifyH(justifyH, ...) end
---@param justifyV? any
---@param ... any
function __WowWidget:SetJustifyV(justifyV, ...) end
---@param keepModelOnHide? boolean
---@param ... any
function __WowWidget:SetKeepModelOnHide(keepModelOnHide, ...) end
---@param enabled? boolean
---@param light? any
---@param ... any
function __WowWidget:SetLight(enabled, light, ...) end
---@param colorR? number
---@param colorG? number
---@param colorB? number
---@param ... any
function __WowWidget:SetLightAmbientColor(colorR, colorG, colorB, ...) end
---@param colorR? number
---@param colorG? number
---@param colorB? number
---@param ... any
function __WowWidget:SetLightDiffuseColor(colorR, colorG, colorB, ...) end
---@param directionX? number
---@param directionY? number
---@param directionZ? number
---@param ... any
function __WowWidget:SetLightDirection(directionX, directionY, directionZ, ...) end
---@param positionX? number
---@param positionY? number
---@param positionZ? number
---@param ... any
function __WowWidget:SetLightPosition(positionX, positionY, positionZ, ...) end
---@param lightType? any
---@param ... any
function __WowWidget:SetLightType(lightType, ...) end
---@param visible? boolean
---@param ... any
function __WowWidget:SetLightVisible(visible, ...) end
---@param uiMapID? number
---@param ... any
function __WowWidget:SetMapID(uiMapID, ...) end
---@param scalar? number
---@param ... any
function __WowWidget:SetMaskScalar(scalar, ...) end
---@param asset? any
---@param ... any
function __WowWidget:SetMaskTexture(asset, ...) end
--- Sets the maximum interval band used for formatting.
---@param interval? any
---@param ... any
function __WowWidget:SetMaxInterval(interval, ...) end
--- Sets the maximum interval band used for formatting to a curve that will be evaluated with seconds values to produce a value matching a SecondsFormatterInterval enum member.
---@param curve? any
---@param ... any
function __WowWidget:SetMaxIntervalCurve(curve, ...) end
---@param maxSnapshots? number
---@param ... any
function __WowWidget:SetMaxSnapshots(maxSnapshots, ...) end
--- Changes the calculation mode for maximum health values used for clamping.
---@param maximumHealthMode? any
---@param ... any
function __WowWidget:SetMaximumHealthMode(maximumHealthMode, ...) end
---@param threshold? number
---@param ... any
function __WowWidget:SetMergeThreshold(threshold, ...) end
--- Sets the threshold below which a value will be formatted as a decimal number of seconds with one place for milliseconds (eg. '3.4')
---@param threshold? any
---@param ... any
function __WowWidget:SetMillisecondsThreshold(threshold, ...) end
--- Sets the minimum interval band used for formatting.
---@param interval? any
---@param ... any
function __WowWidget:SetMinInterval(interval, ...) end
--- Sets the minimum interval band used for formatting to a curve that will be evaluated with seconds values to produce a value matching a SecondsFormatterInterval enum member.
---@param curve? any
---@param ... any
function __WowWidget:SetMinIntervalCurve(curve, ...) end
---@param minValue? number
---@param maxValue? number
---@param ... any
function __WowWidget:SetMinMaxValues(minValue, maxValue, ...) end
---@param asset? any
---@param noMip? boolean
---@param ... any
function __WowWidget:SetModel(asset, noMip, ...) end
---@param alpha? number
---@param ... any
function __WowWidget:SetModelAlpha(alpha, ...) end
---@param creatureDisplayID? number
---@param useActivePlayerCustomizations? boolean
---@param ... any
---@return boolean success
function __WowWidget:SetModelByCreatureDisplayID(creatureDisplayID, useActivePlayerCustomizations, ...) end
---@param asset? any
---@param useMips? boolean
---@param ... any
---@return boolean success
function __WowWidget:SetModelByFileID(asset, useMips, ...) end
---@param link? string
---@param ... any
---@return boolean success
function __WowWidget:SetModelByHyperlink(link, ...) end
---@param asset? any
---@param useMips? boolean
---@param ... any
---@return boolean success
function __WowWidget:SetModelByPath(asset, useMips, ...) end
---@param unit? any
---@param sheatheWeapons? boolean
---@param autoDress? boolean
---@param hideWeapons? boolean
---@param usePlayerNativeForm? boolean
---@param holdBowString? boolean
---@param customRaceID? number
---@param ... any
---@return boolean success
function __WowWidget:SetModelByUnit(unit, sheatheWeapons, autoDress, hideWeapons, usePlayerNativeForm, holdBowString, customRaceID, ...) end
---@param layer? any
---@param ... any
function __WowWidget:SetModelDrawLayer(layer, ...) end
---@param scale? number
---@param ... any
function __WowWidget:SetModelScale(scale, ...) end
---@param numSplinePoints? number
---@param ... any
function __WowWidget:SetNumSplinePoints(numSplinePoints, ...) end
---@param enabled? boolean
---@param ... any
function __WowWidget:SetObeyHideInTransmogFlag(enabled, ...) end
---@param obeyStepOnDrag? boolean
---@param ... any
function __WowWidget:SetObeyStepOnDrag(obeyStepOnDrag, ...) end
---@param offsetU? number
---@param offsetV? number
---@param ... any
function __WowWidget:SetOffset(offsetU, offsetV, ...) end
---@param order? number
---@param ... any
function __WowWidget:SetOrder(order, ...) end
---@param orientation? any
---@param ... any
function __WowWidget:SetOrientation(orientation, ...) end
---@param point? any
---@param originX? number
---@param originY? number
---@param ... any
function __WowWidget:SetOrigin(point, originX, originY, ...) end
---@param asset? any
---@param ... any
function __WowWidget:SetPOIArrowTexture(asset, ...) end
---@param scale? number
---@param ... any
function __WowWidget:SetPanDistance(scale, ...) end
---@param parent? any
---@param order? number
---@param ... any
function __WowWidget:SetParent(parent, order, ...) end
---@param scale? number
---@param ... any
function __WowWidget:SetParticleOverrideScale(scale, ...) end
---@param enabled? boolean
---@param ... any
function __WowWidget:SetParticlesEnabled(enabled, ...) end
---@param paused? boolean
---@param affectsGlobalPause? boolean
---@param ... any
function __WowWidget:SetPaused(paused, affectsGlobalPause, ...) end
---@param pitch? number
---@param ... any
function __WowWidget:SetPitch(pitch, ...) end
---@param characterIndex? number
---@param sheatheWeapons? boolean
---@param autoDress? boolean
---@param hideWeapons? boolean
---@param usePlayerNativeForm? boolean
---@param customRaceID? number
---@param ... any
---@return boolean success
function __WowWidget:SetPlayerModelFromGlues(characterIndex, sheatheWeapons, autoDress, hideWeapons, usePlayerNativeForm, customRaceID, ...) end
---@param scale? number
---@param ... any
function __WowWidget:SetPlayerPingScale(scale, ...) end
---@param textureType? any
---@param asset? any
---@param width? number
---@param height? number
---@param ... any
function __WowWidget:SetPlayerPingTexture(textureType, asset, width, height, ...) end
---@param asset? any
---@param ... any
function __WowWidget:SetPlayerTexture(asset, ...) end
---@param point? any
---@param relativeTo? any
---@param relativePoint? any
---@param offsetX? number
---@param offsetY? number
---@param ... any
function __WowWidget:SetPoint(point, relativeTo, relativePoint, offsetX, offsetY, ...) end
--- Replaces all points on the curve.
---@param point? table
---@param ... any
function __WowWidget:SetPoints(point, ...) end
---@param x? number
---@param y? number
---@param ... any
function __WowWidget:SetPointsOffset(x, y, ...) end
---@param zoom? number
---@param ... any
function __WowWidget:SetPortraitZoom(zoom, ...) end
---@param positionX? number
---@param positionY? number
---@param positionZ? number
---@param ... any
function __WowWidget:SetPosition(positionX, positionY, positionZ, ...) end
--- Sets the healing values used for all calculations.
---@param predictedValues? any
---@param ... any
function __WowWidget:SetPredictedValues(predictedValues, ...) end
--- If true, will try to use the collision bounds of models for sizing and centering. Will fall back to default model bounds if set to False, or if collision bounds are unavailable.
---@param preferCollisionBounds? boolean
---@param ... any
function __WowWidget:SetPreferModelCollisionBounds(preferCollisionBounds, ...) end
---@param alpha? number
---@param ... any
function __WowWidget:SetQuestBlobInsideAlpha(alpha, ...) end
---@param asset? any
---@param ... any
function __WowWidget:SetQuestBlobInsideTexture(asset, ...) end
---@param alpha? number
---@param ... any
function __WowWidget:SetQuestBlobOutsideAlpha(alpha, ...) end
---@param asset? any
---@param ... any
function __WowWidget:SetQuestBlobOutsideTexture(asset, ...) end
---@param alpha? number
---@param ... any
function __WowWidget:SetQuestBlobRingAlpha(alpha, ...) end
---@param scalar? number
---@param ... any
function __WowWidget:SetQuestBlobRingScalar(scalar, ...) end
---@param asset? any
---@param ... any
function __WowWidget:SetQuestBlobRingTexture(asset, ...) end
---@param angle? number
---@param ... any
function __WowWidget:SetRadians(angle, ...) end
---@param callback? any
---@param ... any
function __WowWidget:SetResultsUpdatedCallback(callback, ...) end
---@param roll? number
---@param ... any
function __WowWidget:SetRoll(roll, ...) end
---@param radians? number
---@param animate? boolean
---@param ... any
function __WowWidget:SetRotation(radians, animate, ...) end
---@param scale? number
---@param ... any
function __WowWidget:SetScale(scale, ...) end
---@param scaleX? number
---@param scaleY? number
---@param ... any
function __WowWidget:SetScaleFrom(scaleX, scaleY, ...) end
---@param scaleX? number
---@param scaleY? number
---@param ... any
function __WowWidget:SetScaleTo(scaleX, scaleY, ...) end
--- Search parameter; If set, multiple text fields are checked for instances of the text, including name, category, subcategory, and data tags
---@param searchText? string
---@param ... any
function __WowWidget:SetSearchText(searchText, ...) end
---@param sequence? number
---@param ... any
function __WowWidget:SetSequence(sequence, ...) end
---@param sequence? number
---@param timeOffset? number
---@param ... any
function __WowWidget:SetSequenceTime(sequence, timeOffset, ...) end
---@param colorR? number
---@param colorG? number
---@param colorB? number
---@param a? any
---@param ... any
function __WowWidget:SetShadowColor(colorR, colorG, colorB, a, ...) end
---@param strength? number
---@param ... any
function __WowWidget:SetShadowEffect(strength, ...) end
---@param offsetX? number
---@param offsetY? number
---@param ... any
function __WowWidget:SetShadowOffset(offsetX, offsetY, ...) end
---@param sheathed? boolean
---@param hideWeapons? boolean
---@param ... any
function __WowWidget:SetSheathed(sheathed, hideWeapons, ...) end
---@param inventorySlots? number
---@param category? any
---@param ... any
function __WowWidget:SetSheathedCategory(inventorySlots, category, ...) end
---@param show? boolean
---@param ... any
function __WowWidget:SetShown(show, ...) end
---@param x? number
---@param y? number
---@param ... any
function __WowWidget:SetSize(x, y, ...) end
---@param sortType? any
---@param ... any
function __WowWidget:SetSortType(sortType, ...) end
---@param spacing? number
---@param ... any
function __WowWidget:SetSpacing(spacing, ...) end
---@param visualKitID? number
---@param ... any
function __WowWidget:SetSpellVisualKit(visualKitID, ...) end
---@param frame? any
---@param ... any
function __WowWidget:SetStackingBoundsFrame(frame, ...) end
---@param color? any
---@param ... any
function __WowWidget:SetStartColor(color, ...) end
---@param relativePoint? any
---@param relativeTo? any
---@param offsetX? number
---@param offsetY? number
---@param ... any
function __WowWidget:SetStartPoint(relativePoint, relativeTo, offsetX, offsetY, ...) end
---@param asset? any
---@param ... any
function __WowWidget:SetStaticPOIArrowTexture(asset, ...) end
---@param stepsPerPage? number
---@param ... any
function __WowWidget:SetStepsPerPage(stepsPerPage, ...) end
--- Search parameter; If true, only entries that you have instances of available in storage will be included; This does not include entries that you own but have all been placed in a house; See IsCollectedActive for param that includes placed entries
---@param isActive? boolean
---@param ... any
function __WowWidget:SetStoredOnly(isActive, ...) end
--- Sets the whitespace stripping mode for the formatter.
---@param strip? any
---@param ... any
function __WowWidget:SetStripIntervalWhitespace(strip, ...) end
---@param scale? number
---@param ... any
function __WowWidget:SetTargetDistance(scale, ...) end
---@param alpha? number
---@param ... any
function __WowWidget:SetTaskBlobInsideAlpha(alpha, ...) end
---@param asset? any
---@param ... any
function __WowWidget:SetTaskBlobInsideTexture(asset, ...) end
---@param alpha? number
---@param ... any
function __WowWidget:SetTaskBlobOutsideAlpha(alpha, ...) end
---@param asset? any
---@param ... any
function __WowWidget:SetTaskBlobOutsideTexture(asset, ...) end
---@param alpha? number
---@param ... any
function __WowWidget:SetTaskBlobRingAlpha(alpha, ...) end
---@param scalar? number
---@param ... any
function __WowWidget:SetTaskBlobRingScalar(scalar, ...) end
---@param asset? any
---@param ... any
function __WowWidget:SetTaskBlobRingTexture(asset, ...) end
---@param colorR? number
---@param colorG? number
---@param colorB? number
---@param a? any
---@param ... any
function __WowWidget:SetTextColor(colorR, colorG, colorB, a, ...) end
---@param thickness? number
---@param ... any
function __WowWidget:SetThickness(thickness, ...) end
---@param asset? any
---@param ... any
function __WowWidget:SetThumbTexture(asset, ...) end
--- Configures the duration object to represent an end time and a duration.
---@param endTime? any
---@param duration? any
---@param modRate? number
---@param ... any
function __WowWidget:SetTimeFromEnd(endTime, duration, modRate, ...) end
--- Configures the duration object to represent a start time and a duration.
---@param startTime? any
---@param duration? any
---@param modRate? number
---@param ... any
function __WowWidget:SetTimeFromStart(startTime, duration, modRate, ...) end
--- Configures the duration object to represent a fixed start and end time span. If the end time is earlier than the start time, the duration will clamp to zero.
---@param startTime? any
---@param endTime? any
---@param ... any
function __WowWidget:SetTimeSpan(startTime, endTime, ...) end
---@param timeVisibleSeconds? number
---@param ... any
function __WowWidget:SetTimeVisible(timeVisibleSeconds, ...) end
---@param normalizedAlpha? number
---@param ... any
function __WowWidget:SetToAlpha(normalizedAlpha, ...) end
--- Resets all state on the curve, and clears the secret values flag.
---@param ... any
function __WowWidget:SetToDefaults(...) end
---@param translation? any
---@param rotation? any
---@param scale? number
---@param ... any
function __WowWidget:SetTransform(translation, rotation, scale, ...) end
--- Changes the evaluation type of the curve.
---@param type? any
---@param ... any
function __WowWidget:SetType(type, ...) end
---@param uiMapID? number
---@param ... any
function __WowWidget:SetUiMapID(uiMapID, ...) end
--- Search parameter; If true, includes entries that are not owned, meaning not available in storage nor placed in any owned houses or plots
---@param isActive? boolean
---@param ... any
function __WowWidget:SetUncollected(isActive, ...) end
---@param unit? any
---@param blend? boolean
---@param useNativeForm? boolean
---@param ... any
---@return boolean success
function __WowWidget:SetUnit(unit, blend, useNativeForm, ...) end
---@param unit? any
---@param colorR? number
---@param colorG? number
---@param colorB? number
---@param colorA? number
---@param ... any
function __WowWidget:SetUnitColor(unit, colorR, colorG, colorB, colorA, ...) end
---@param cb? any
---@param ... any
function __WowWidget:SetUpdateCallback(cb, ...) end
---@param x? boolean
---@param y? boolean
---@param z? boolean
---@param ... any
function __WowWidget:SetUseCenterForOrigin(x, y, z, ...) end
---@param useGBuffer? boolean
---@param ... any
function __WowWidget:SetUseGBuffer(useGBuffer, ...) end
---@param enabled? boolean
---@param ... any
function __WowWidget:SetUseTransmogChoices(enabled, ...) end
---@param enabled? boolean
---@param ... any
function __WowWidget:SetUseTransmogSkin(enabled, ...) end
---@param value? number
---@param treatAsMouseEvent? boolean
---@param ... any
function __WowWidget:SetValue(value, treatAsMouseEvent, ...) end
---@param valueStep? number
---@param ... any
function __WowWidget:SetValueStep(valueStep, ...) end
---@param insets? any
---@param ... any
function __WowWidget:SetViewInsets(insets, ...) end
---@param translationX? number
---@param translationY? number
---@param ... any
function __WowWidget:SetViewTranslation(translationX, translationY, ...) end
---@param width? number
---@param ... any
function __WowWidget:SetWidth(width, ...) end
---@param yaw? number
---@param ... any
function __WowWidget:SetYaw(yaw, ...) end
---@param zoomLevel? number
---@param ... any
function __WowWidget:SetZoom(zoomLevel, ...) end
---@param ... any
function __WowWidget:Show(...) end
---@param movieID? number
---@param looping? boolean
---@param ... any
---@return boolean success
---@return number returnCode
function __WowWidget:StartMovie(movieID, looping, ...) end
---@param movieName? string
---@param looping? boolean
---@param resolution? number
---@param ... any
---@return boolean success
---@return number returnCode
function __WowWidget:StartMovieByName(movieName, looping, resolution, ...) end
---@param panType? number
---@param durationSeconds? number
---@param doFade? boolean
---@param visKitID? number
---@param startPositionScale? number
---@param speedMultiplier? number
---@param ... any
function __WowWidget:StartPan(panType, durationSeconds, doFade, visKitID, startPositionScale, speedMultiplier, ...) end
---@param duration? number
---@param fadeDuration? number
---@param ... any
function __WowWidget:StartPlayerPing(duration, fadeDuration, ...) end
---@param ... any
function __WowWidget:StopAnimKit(...) end
---@param ... any
function __WowWidget:StopAnimating(...) end
---@param ... any
function __WowWidget:StopAnimationKit(...) end
---@param ... any
function __WowWidget:StopMovie(...) end
---@param ... any
function __WowWidget:StopPan(...) end
---@param ... any
function __WowWidget:StopPlayerPing(...) end
---@param ... any
function __WowWidget:TakeActor(...) end
---@param ... any
---@return number snapshotID
function __WowWidget:TakeSnapshot(...) end
--- Unavailable in public builds
---@param snapshotID? number
---@param filename? string
---@param ... any
---@return boolean success
function __WowWidget:TestPrintToFile(snapshotID, filename, ...) end
---@param ... any
function __WowWidget:ToggleAllowedIndoors(...) end
---@param ... any
function __WowWidget:ToggleAllowedOutdoors(...) end
---@param ... any
function __WowWidget:ToggleBaseVariantOnly(...) end
---@param ... any
function __WowWidget:ToggleCollected(...) end
---@param ... any
function __WowWidget:ToggleCustomizableOnly(...) end
---@param groupID? number
---@param tagID? number
---@param ... any
function __WowWidget:ToggleFilterTag(groupID, tagID, ...) end
---@param ... any
function __WowWidget:ToggleFirstAcquisitionBonusOnly(...) end
---@param ... any
function __WowWidget:ToggleStoredOnly(...) end
---@param ... any
function __WowWidget:ToggleUncollected(...) end
---@param cameraPosition? any
---@param ... any
---@return any modelPosition
function __WowWidget:TransformCameraSpaceToModelSpace(cameraPosition, ...) end
---@param linkOrItemModifiedAppearanceID? any
---@param handSlotName? string
---@param spellEnchantID? number
---@param ... any
---@return any result
function __WowWidget:TryOn(linkOrItemModifiedAppearanceID, handSlotName, spellEnchantID, ...) end
---@param ... any
function __WowWidget:Undress(...) end
---@param inventorySlot? number
---@param ... any
function __WowWidget:UndressSlot(inventorySlot, ...) end
---@param ... any
function __WowWidget:UnequipItems(...) end
---@param ... any
function __WowWidget:UpdateBlips(...) end
---@param x? number
---@param y? number
---@param ... any
---@return number questID
---@return number numObjectives
function __WowWidget:UpdateMouseOverTooltip(x, y, ...) end
---@param useCenter? boolean
---@param ... any
function __WowWidget:UseModelCenterToTransform(useCenter, ...) end
---@param useCategory? boolean
---@param ... any
function __WowWidget:UseUnitSheatheCategory(useCategory, ...) end
---@param ... any
---@return boolean usesNPOT
function __WowWidget:UsesNPOT(...) end
---@param ... any
function __WowWidget:ZeroCachedCenterXY(...) end

---@class Region : __WowWidget
---@class Frame : __WowWidget
---@class Texture : __WowWidget
---@class MaskTexture : __WowWidget
---@class Line : __WowWidget
---@class FontString : __WowWidget
---@class Button : __WowWidget
---@class CheckButton : __WowWidget
---@class StatusBar : __WowWidget
---@class Slider : __WowWidget
---@class EditBox : __WowWidget
---@class ScrollFrame : __WowWidget
---@class Cooldown : __WowWidget
---@class Model : __WowWidget
---@class PlayerModel : __WowWidget
---@class ModelScene : __WowWidget
---@class Animation : __WowWidget
---@class AnimationGroup : __WowWidget
---@class ColorSelect : __WowWidget
---@class MessageFrame : __WowWidget
---@class ScrollingMessageFrame : __WowWidget
---@class SimpleHTML : __WowWidget
---@class Browser : __WowWidget
---@class MovieFrame : __WowWidget
---@class FontInstance : __WowWidget
