--[[
    QUI-maintained list of movable Blizzard panel roots (global names / dotted paths).
]]

local _, ns = ...
local M = ns.QUI_BlizzardMover
if not M then return end

-- Consumed from blizzard_mover.lua during InitRegistry() after both files load.
M._FrameRegistryData = {
	groupOrder = {
		system = 10,
		character = 20,
		housing = 25,
		activities = 30,
		world = 40,
		bags = 50,
		vendors = 60,
		professions = 70,
		addons = 80,
	},

	groups = {
		system = {
			label = ns.L["System"],
			expanded = true,
		},
		character = {
			label = ns.L["Character"],
		},
		housing = {
			label = ns.L["Housing"],
			expanded = true,
		},
		activities = {
			label = ns.L["Activities"],
		},
		world = {
			label = ns.L["World"],
		},
		bags = {
			label = ns.L["Bags & Bank"],
		},
		vendors = {
			label = ns.L["Vendors"],
		},
		professions = {
			label = ns.L["Professions"],
		},
		addons = {
			label = ns.L["Addons"],
		},
	},

	frames = {
		{
			id = "SettingsPanel",
			label = ns.L["Settings"],
			group = "system",
			names = { "SettingsPanel" },
			addon = "Blizzard_Settings",
			defaultEnabled = true,
		},
		{
			id = "SplashFrame",
			label = ns.L["What's New"],
			group = "system",
			names = { "SplashFrame" },
			defaultEnabled = true,
		},
		{
			id = "GameMenuFrame",
			label = ns.L["Game Menu"],
			group = "system",
			names = { "GameMenuFrame" },
			addon = "Blizzard_GameMenu",
			handlesRelative = { "Header" },
			skipOnHide = true,
			defaultEnabled = true,
		},
		{
			id = "MacroFrame",
			label = ns.L["Macros"],
			group = "system",
			names = { "MacroFrame" },
			addon = "Blizzard_MacroUI",
			defaultEnabled = true,
		},
		{
			id = "MacroPopupFrame",
			label = ns.L["Macro Popup"],
			group = "system",
			names = { "MacroPopupFrame" },
			addon = "Blizzard_MacroUI",
			defaultEnabled = true,
		},
		{
			id = "AddonList",
			label = ns.L["Addon List"],
			group = "system",
			names = { "AddonList" },
			defaultEnabled = true,
		},
		{
			id = "CatalogShopFrame",
			label = ns.L["Blizzard Shop"],
			group = "system",
			names = { "CatalogShopFrame" },
			defaultEnabled = true,
		},
		{
			id = "AchievementFrame",
			label = ns.L["Achievements"],
			group = "character",
			names = { "AchievementFrame" },
			addon = "Blizzard_AchievementUI",
			handlesRelative = { "Header" },
			defaultEnabled = true,
		},
		{
			id = "HousingControlsFrame",
			label = ns.L["Housing Controls"],
			group = "housing",
			names = { "HousingControlsFrame" },
			addon = "Blizzard_HousingControls",
			handlesRelative = { "OwnerControlFrame" },
			defaultEnabled = true,
		},
		{
			id = "HousingDashboardFrame",
			label = ns.L["Housing Dashboard"],
			group = "housing",
			names = { "HousingDashboardFrame" },
			addon = "Blizzard_HousingDashboard",
			defaultEnabled = true,
		},
		{
			id = "HouseFinderFrame",
			label = ns.L["House Finder"],
			group = "housing",
			names = { "HouseFinderFrame" },
			addon = "Blizzard_HousingHouseFinder",
			defaultEnabled = true,
		},
		{
			id = "HouseListFrame",
			label = ns.L["House List"],
			group = "housing",
			names = { "HouseListFrame" },
			addon = "Blizzard_HouseList",
			defaultEnabled = true,
		},
		{
			id = "HousingHouseSettingsFrame",
			label = ns.L["Housing Settings"],
			group = "housing",
			names = { "HousingHouseSettingsFrame" },
			addon = "Blizzard_HousingHouseSettings",
			defaultEnabled = true,
		},
		{
			id = "AbandonHouseConfirmationDialog",
			label = ns.L["Abandon House"],
			group = "housing",
			names = { "AbandonHouseConfirmationDialog" },
			addon = "Blizzard_HousingHouseSettings",
			defaultEnabled = true,
		},
		{
			id = "HousingCornerstoneVisitorFrame",
			label = ns.L["Housing Cornerstone Visitor"],
			group = "housing",
			names = { "HousingCornerstoneVisitorFrame", "HousingCornerstoneHouseInfoFrame" },
			addon = "Blizzard_HousingCornerstone",
			defaultEnabled = true,
		},
		{
			id = "HousingModelPreviewFrame",
			label = ns.L["Housing Model Preview"],
			group = "housing",
			names = { "HousingModelPreviewFrame" },
			addon = "Blizzard_HousingModelPreview",
			defaultEnabled = true,
		},
		{
			id = "CharacterFrame",
			label = ns.L["Character"],
			group = "character",
			names = { "CharacterFrame" },
			defaultEnabled = true,
		},
		{
			id = "CooldownViewerSettings",
			label = HUD_EDIT_MODE_COOLDOWN_VIEWER_OPTIONS,
			group = "character",
			names = { "CooldownViewerSettings" },
			addon = "Blizzard_CooldownViewer",
			defaultEnabled = true,
		},
		{
			id = "InspectFrame",
			label = INSPECT,
			group = "character",
			names = { "InspectFrame" },
			defaultEnabled = true,
			addon = "Blizzard_InspectUI",
		},
		{
			id = "PlayerSpellsFrame",
			label = ns.L["Talents & Spells"],
			group = "character",
			names = { "PlayerSpellsFrame" },
			handlesRelative = { "TalentsFrame", "SpecFrame" },
			addon = "Blizzard_PlayerSpells",
			-- Defer the SetPoint re-assert one frame: a synchronous re-anchor
			-- mid hero-talent-tree rebuild trips 12.0's anchor-family guard.
			-- Every other panel re-asserts synchronously (no flicker).
			deferReassert = true,
			defaultEnabled = true,
		},
		-- PROTOTYPE (in-game verification PENDING) — the dialog is packed with
		-- talent buttons reparented from the live tree whose edges weave them
		-- into one anchor family. Earlier QUI attempts pinned the moved dialog to
		-- the REAL UIParent (it inherits DefaultPanelTemplate = NOT protected, so
		-- it never took the secure path) and tripped 12.0's anchor-family guard
		-- during the tree rebuild (PlaceHeroTalentButton, ...Dialog.lua:442). The
		-- reference mover DOES move this dialog, but only ever anchors moved
		-- frames to a UIParent-MIRRORING proxy, never UIParent itself — a
		-- difference QUI never tested on the dialog. proxyParent routes the
		-- re-anchor through QUI_MoverSecureAnchor (our same mirror) to test
		-- whether a distinct anchor node avoids the trip; deferReassert keeps the
		-- re-anchor out of any synchronous rebuild pass. If 442 still fires
		-- in-game, the conflict is local to NodesContainer (proxy-independent) —
		-- remove this panel again, now genuinely exhaustive.
		{
			id = "HeroTalentsSelectionDialog",
			label = ns.L["Hero Talents"],
			group = "character",
			names = { "HeroTalentsSelectionDialog" },
			addon = "Blizzard_PlayerSpells",
			proxyParent = true,
			deferReassert = true,
			defaultEnabled = true,
		},
		{
			id = "PVEFrame",
			label = ns.L["Group Finder"],
			group = "activities",
			names = { "PVEFrame" },
			defaultEnabled = true,
		},
		{
			id = "PVPMatchResults",
			label = ns.L["PvP Match Results"],
			group = "activities",
			names = { "PVPMatchResults" },
			addon = "Blizzard_PVPMatch",
			defaultEnabled = true,
		},
		{
			id = "QueueStatusButton",
			label = ns.L["Queue Status Button"],
			group = "activities",
			names = { "QueueStatusButton" },
			addon = "Blizzard_QueueStatusFrame",
			skipOnHide = true,
			defaultEnabled = false,
		},
		{
			id = "EncounterJournal",
			label = ADVENTURE_JOURNAL,
			group = "activities",
			names = { "EncounterJournal" },
			addon = "Blizzard_EncounterJournal",
			defaultEnabled = true,
		},
		{
			id = "LFGDungeonReadyDialog",
			label = ns.L["Dungeon Ready Dialog"],
			group = "activities",
			names = { "LFGDungeonReadyDialog" },
			defaultEnabled = true,
		},
		{
			id = "LFGListInviteDialog",
			label = ns.L["LFG List Invite Dialog"],
			group = "activities",
			names = { "LFGListInviteDialog" },
			defaultEnabled = true,
		},
		{
			id = "ReadyCheckFrame",
			label = ns.L["Ready Check"],
			group = "activities",
			names = { "ReadyCheckFrame" },
			defaultEnabled = true,
		},
		{
			id = "WeeklyRewardsFrame",
			label = ns.L["Great Vault"],
			group = "activities",
			names = { "WeeklyRewardsFrame" },
			addon = "Blizzard_WeeklyRewards",
			defaultEnabled = true,
		},
		{
			id = "DelvesCompanionConfigurationFrame",
			label = ns.L["Delves Companion"],
			group = "activities",
			names = { "DelvesCompanionConfigurationFrame" },
			addon = "Blizzard_DelvesDashboardUI",
			handlesRelative = { "CompanionPortraitFrame" },
			defaultEnabled = true,
		},
		{
			id = "TransmogFrame",
			label = ns.L["Transmog Frame"],
			group = "system",
			names = { "TransmogFrame" },
			addon = "Blizzard_Transmog",
			defaultEnabled = true,
		},
		{
			id = "DelvesCompanionAbilityListFrame",
			label = ns.L["Delves Companion Abilities"],
			group = "activities",
			names = { "DelvesCompanionAbilityListFrame" },
			addon = "Blizzard_DelvesDashboardUI",
			defaultEnabled = true,
		},
		{
			id = "ChallengesKeystoneFrame",
			label = ns.L["Font of Power"],
			group = "activities",
			names = { "ChallengesKeystoneFrame" },
			addon = "Blizzard_ChallengesUI",
			defaultEnabled = true,
		},
		{
			id = "ItemInteractionFrame",
			label = ns.L["Catalyst"],
			group = "character",
			names = { "ItemInteractionFrame" },
			addon = "Blizzard_ItemInteractionUI",
			defaultEnabled = true,
		},
		{
			id = "PlayerChoiceFrame",
			label = ns.L["Player Choice"],
			group = "character",
			names = { "PlayerChoiceFrame" },
			addon = "Blizzard_PlayerChoice",
			defaultEnabled = true,
		},
		{
			id = "WorldMapFrame",
			label = ns.L["World Map"],
			group = "world",
			names = { "WorldMapFrame" },
			defaultEnabled = true,
			secureFrame = true,
		},
		{
			id = "BattlefieldMapFrame",
			label = BATTLEFIELD_MINIMAP,
			group = "world",
			names = { "BattlefieldMapFrame" },
			addon = "Blizzard_BattlefieldMap",
			disableMove = true,
			scaleTargets = { "BattlefieldMapTab" },
			defaultEnabled = true,
		},
		{
			id = "UIWidgetBelowMinimapContainerFrame",
			label = ns.L["Below Minimap Widgets"],
			group = "world",
			names = { "UIWidgetBelowMinimapContainerFrame" },
			addon = "Blizzard_UIWidgets",
			ignoreFramePositionManager = true,
			defaultEnabled = false,
		},
		{
			id = "UIWidgetPowerBarContainerFrame",
			label = ns.L["Power Bar Widgets"],
			group = "world",
			names = { "UIWidgetPowerBarContainerFrame" },
			addon = "Blizzard_UIWidgets",
			defaultEnabled = false,
		},
		{
			id = "UIWidgetTopCenterContainerFrame",
			label = ns.L["Top Center Widgets"],
			group = "world",
			names = { "UIWidgetTopCenterContainerFrame" },
			addon = "Blizzard_UIWidgets",
			defaultEnabled = false,
		},
		{
			id = "FlightMapFrame",
			label = ns.L["Flight Map"],
			group = "world",
			names = { "FlightMapFrame" },
			addon = "Blizzard_FlightMap",
			defaultEnabled = true,
		},
		{
			id = "ContainerFrameCombinedBags",
			label = ns.L["Combined Bags"],
			group = "bags",
			names = { "ContainerFrameCombinedBags" },
			defaultEnabled = true,
		},
		{
			id = "ItemUpgradeFrame",
			label = ns.L["Item Upgrade"],
			group = "vendors",
			names = { "ItemUpgradeFrame" },
			addon = "Blizzard_ItemUpgradeUI",
			defaultEnabled = true,
		},
		{
			id = "ItemSocketingFrame",
			label = ITEM_SOCKETING,
			group = "vendors",
			names = { "ItemSocketingFrame" },
			addon = "Blizzard_ItemSocketingUI",
			defaultEnabled = true,
		},
		{
			id = "ExpansionLandingPage",
			label = ns.L["Expansion Landing Page"],
			group = "activities",
			names = { "ExpansionLandingPage" },
			addon = "Blizzard_MajorFactions",
			defaultEnabled = true,
		},
		{
			id = "MajorFactionRenownFrame",
			label = ns.L["Renown"],
			group = "activities",
			names = { "MajorFactionRenownFrame" },
			handlesRelative = { "HeaderFrame" },
			addon = "Blizzard_MajorFactions",
			defaultEnabled = true,
		},
		{
			id = "ProfessionsCustomerOrdersFrame",
			label = ns.L["Customer Orders"],
			group = "professions",
			names = { "ProfessionsCustomerOrdersFrame" },
			addon = "Blizzard_ProfessionsCustomerOrders",
			defaultEnabled = true,
		},
		{
			id = "MerchantFrame",
			label = ns.L["Merchant"],
			group = "vendors",
			names = { "MerchantFrame" },
			defaultEnabled = true,
			ignoreFramePositionManager = true,
			userPlaced = true,
		},
		{
			id = "AuctionHouseFrame",
			label = ns.L["Auction House"],
			group = "vendors",
			names = { "AuctionHouseFrame" },
			addon = "Blizzard_AuctionHouseUI",
			defaultEnabled = true,
		},
		{
			id = "CurrencyTransferMenu",
			label = ns.L["Currency Transfer"],
			group = "vendors",
			names = { "CurrencyTransferMenu" },
			addon = "Blizzard_TokenUI",
			defaultEnabled = true,
		},
		{
			id = "MailFrame",
			label = ns.L["Mail"],
			group = "vendors",
			names = { "MailFrame" },
			addon = "Blizzard_MailFrame",
			useRootHandle = true,
			handles = { "SendMailFrame", "MailFrameInset" },
			secureFrame = true,
			defaultEnabled = true,
		},
		{
			id = "OpenMailFrame",
			label = ns.L["Open Mail"],
			group = "vendors",
			names = { "OpenMailFrame" },
			addon = "Blizzard_MailFrame",
			useRootHandle = true,
			handles = { "OpenMailSender", "OpenMailFrameInset" },
			secureFrame = true,
			defaultEnabled = true,
		},
		{
			id = "ChatConfigFrame",
			label = ns.L["Chat Settings"],
			group = "system",
			names = { "ChatConfigFrame" },
			defaultEnabled = true,
		},
		{
			id = "HelpFrame",
			label = ns.L["Support"],
			group = "system",
			names = { "HelpFrame" },
			addon = "Blizzard_HelpFrame",
			defaultEnabled = true,
		},
		{
			id = "GarrisonCapacitiveDisplayFrame",
			label = ns.L["Garrison"],
			group = "activities",
			names = { "GarrisonCapacitiveDisplayFrame" },
			addon = "Blizzard_GarrisonUI",
			defaultEnabled = true,
		},
		{
			id = "DressUpFrame",
			label = ns.L["Dressing Room"],
			group = "character",
			names = { "DressUpFrame" },
			defaultEnabled = true,
		},
		{
			id = "CommunitiesFrame",
			label = ns.L["Communities"],
			group = "activities",
			names = { "CommunitiesFrame" },
			addon = "Blizzard_Communities",
			defaultEnabled = true,
		},
		{
			id = "ClubFinderCommunityAndGuildFinderFrame",
			label = ns.L["Community & Guild Finder"],
			group = "activities",
			names = { "ClubFinderCommunityAndGuildFinderFrame.RequestToJoinFrame" },
			addon = "Blizzard_Communities",
			defaultEnabled = true,
		},
		{
			id = "ClubFinderGuildFinderFrame",
			label = ns.L["Guild Finder"],
			group = "activities",
			names = { "ClubFinderGuildFinderFrame.RequestToJoinFrame" },
			addon = "Blizzard_Communities",
			defaultEnabled = true,
		},
		{
			id = "CommunitiesGuildLogFrame",
			label = ns.L["Guild Log"],
			group = "activities",
			names = { "CommunitiesGuildLogFrame" },
			addon = "Blizzard_Communities",
			defaultEnabled = true,
		},
		{
			id = "CommunitiesGuildNewsFiltersFrame",
			label = ns.L["Guild News Filters"],
			group = "activities",
			names = { "CommunitiesGuildNewsFiltersFrame" },
			addon = "Blizzard_Communities",
			defaultEnabled = true,
		},
		{
			id = "CommunitiesGuildTextEditFrame",
			label = ns.L["Guild Text Edit"],
			group = "activities",
			names = { "CommunitiesGuildTextEditFrame" },
			addon = "Blizzard_Communities",
			defaultEnabled = true,
		},
		{
			id = "CommunitiesRecruitmentDialog",
			label = ns.L["Community Recruitment"],
			group = "activities",
			names = { "CommunitiesFrame.RecruitmentDialog" },
			addon = "Blizzard_Communities",
			defaultEnabled = true,
		},
		{
			id = "CommunitiesNotificationSettingsDialog",
			label = ns.L["Community Notification Settings"],
			group = "activities",
			names = { "CommunitiesFrame.NotificationSettingsDialog" },
			addon = "Blizzard_Communities",
			defaultEnabled = true,
		},
		{
			id = "FriendsFrame",
			label = ns.L["Friends"],
			group = "activities",
			names = { "FriendsFrame" },
			defaultEnabled = true,
		},
		{
			id = "FriendsFrameIgnoreList",
			label = ns.L["Ignore List"],
			group = "activities",
			names = { "FriendsFrame.IgnoreListWindow" },
			defaultEnabled = true,
		},
		{
			id = "RecruitAFriendRewardsFrame",
			label = ns.L["Recruit A Friend Rewards"],
			group = "activities",
			names = { "RecruitAFriendRewardsFrame" },
			defaultEnabled = true,
		},
		{
			id = "RecruitAFriendRecruitmentFrame",
			label = ns.L["Recruit A Friend"],
			group = "activities",
			names = { "RecruitAFriendRecruitmentFrame" },
			defaultEnabled = true,
		},
		{
			id = "FriendsFriendsFrame",
			label = ns.L["Friends List"],
			group = "activities",
			names = { "FriendsFriendsFrame" },
			defaultEnabled = true,
		},
		{
			id = "RaidInfoFrame",
			label = ns.L["Raid Info"],
			group = "activities",
			names = { "RaidInfoFrame" },
			defaultEnabled = true,
		},
		{
			id = "AddFriendFrame",
			label = ns.L["Add Friend"],
			group = "activities",
			names = { "AddFriendFrame" },
			defaultEnabled = true,
		},
		{
			id = "ClassTrainerFrame",
			label = MINIMAP_TRACKING_TRAINER_CLASS,
			group = "world",
			names = { "ClassTrainerFrame" },
			addon = "Blizzard_TrainerUI",
			defaultEnabled = true,
		},
		{
			id = "BankFrame",
			label = ns.L["Bank"],
			group = "bags",
			names = { "BankFrame" },
			defaultEnabled = true,
		},
		{
			id = "ArtifactFrame",
			label = ns.L["Artifact"],
			group = "character",
			names = { "ArtifactFrame" },
			addon = "Blizzard_ArtifactUI",
			defaultEnabled = true,
		},
		{
			id = "CollectionsJournal",
			label = ns.L["Collections"],
			group = "character",
			names = { "CollectionsJournal" },
			addon = "Blizzard_Collections",
			defaultEnabled = true,
		},
		{
			id = "ProfessionsFrame",
			label = ns.L["Professions"],
			group = "professions",
			names = { "ProfessionsFrame" },
			addon = "Blizzard_Professions",
			defaultEnabled = true,
		},
		{
			id = "ProfessionsBookFrame",
			label = ns.L["Professions Book"],
			group = "professions",
			names = { "ProfessionsBookFrame" },
			addon = "Blizzard_ProfessionsBook",
			defaultEnabled = true,
		},
		{
			id = "QuestFrame",
			label = ns.L["Quest"],
			group = "world",
			names = { "QuestFrame", "GossipFrame" },
			defaultEnabled = true,
		},
		{
			id = "StaticPopup",
			label = ns.L["Static Popups"],
			group = "system",
			-- InstanceAbandonPopup is Blizzard's reserved StaticPopup for the M+
			-- "vote to abandon" prompt. FrameXML hard-anchors it BOTTOMRIGHT and
			-- StaticPopup_SetUpPosition leaves reserved/fixed dialogs at their XML
			-- anchor (no top-stack), so it pops in the corner instead of with the
			-- other popups. Folding it in here shares this entry's saved offset; the
			-- defaultPoint below restores the top-center home for the default case.
			names = { "StaticPopup1", "StaticPopup2", "StaticPopup3", "StaticPopup4", "StaticPopup5", "InstanceAbandonPopup" },
			defaultPoint = { point = "TOP", x = 0, y = -135 },
			defaultEnabled = true,
		},
		{
			id = "EventToastManagerFrame",
			label = ns.L["Event Toasts"],
			group = "system",
			names = { "EventToastManagerFrame" },
			defaultEnabled = true,
		},
		{
			id = "CalendarFrame",
			label = ns.L["Calendar"],
			group = "system",
			names = { "CalendarFrame" },
			addon = "Blizzard_Calendar",
			defaultEnabled = true,
		},
		{
			id = "CalendarViewHolidayFrame",
			label = ns.L["Calendar Holiday"],
			group = "system",
			names = { "CalendarViewHolidayFrame" },
			addon = "Blizzard_Calendar",
			defaultEnabled = true,
		},
		{
			id = "CalendarCreateEventFrame",
			label = ns.L["Calendar Event"],
			group = "system",
			names = { "CalendarCreateEventFrame" },
			addon = "Blizzard_Calendar",
			defaultEnabled = true,
		},
		{
			id = "TimeManagerFrame",
			label = ns.L["Time Manager"],
			group = "system",
			names = { "TimeManagerFrame" },
			addon = "Blizzard_TimeManager",
			defaultEnabled = true,
		},
		{
			id = "CovenantSanctumFrame",
			label = ns.L["Covenant Sanctum Frame"],
			group = "activities",
			names = { "CovenantSanctumFrame" },
			addon = "Blizzard_CovenantSanctum",
			defaultEnabled = true,
		},
		{
			id = "CovenantMissionFrame",
			label = ns.L["Covenant Mission Frame"],
			group = "activities",
			names = { "CovenantMissionFrame" },
			addon = "Blizzard_GarrisonUI",
			defaultEnabled = true,
		},
		{
			id = "CovenantRenownFrame",
			label = ns.L["Covenant Renown Frame"],
			group = "activities",
			names = { "CovenantRenownFrame" },
			addon = "Blizzard_CovenantRenown",
			defaultEnabled = true,
		},
		{
			id = "CovenantPreviewFrame",
			label = ns.L["Covenant Preview Frame"],
			group = "activities",
			names = { "CovenantPreviewFrame" },
			addon = "Blizzard_CovenantPreviewUI",
			defaultEnabled = true,
		},
		{
			id = "GarrisonLandingPage",
			label = ns.L["Garrison Landing Page"],
			group = "activities",
			names = { "GarrisonLandingPage" },
			addon = "Blizzard_GarrisonUI",
			defaultEnabled = true,
		},
	}
}
