--[[
    QUI-maintained list of movable Blizzard panel roots (global names / dotted paths).
]]

local _, ns = ...
local M = ns.QUI_BlizzardMover
if not M then return end

-- Consumed from blizzard_mover.lua during InitRegistry() after both files load.
M._FrameRegistryData = {
	groupOrder = {
		system = 10,
		character = 20,
		housing = 25,
		activities = 30,
		world = 40,
		bags = 50,
		vendors = 60,
		professions = 70,
		addons = 80,
	},

	groups = {
		system = {
			label = "System",
			expanded = true,
		},
		character = {
			label = "Character",
		},
		housing = {
			label = "Housing",
			expanded = true,
		},
		activities = {
			label = "Activities",
		},
		world = {
			label = "World",
		},
		bags = {
			label = "Bags & Bank",
		},
		vendors = {
			label = "Vendors",
		},
		professions = {
			label = "Professions",
		},
		addons = {
			label = "Addons",
		},
	},

	frames = {
		{
			id = "SettingsPanel",
			label = "Settings",
			group = "system",
			names = { "SettingsPanel" },
			addon = "Blizzard_Settings",
			defaultEnabled = true,
		},
		{
			id = "SplashFrame",
			label = "What's New",
			group = "system",
			names = { "SplashFrame" },
			defaultEnabled = true,
		},
		{
			id = "GameMenuFrame",
			label = "Game Menu",
			group = "system",
			names = { "GameMenuFrame" },
			addon = "Blizzard_GameMenu",
			handlesRelative = { "Header" },
			skipOnHide = true,
			defaultEnabled = true,
		},
		{
			id = "MacroFrame",
			label = "Macros",
			group = "system",
			names = { "MacroFrame" },
			addon = "Blizzard_MacroUI",
			defaultEnabled = true,
		},
		{
			id = "MacroPopupFrame",
			label = "Macro Popup",
			group = "system",
			names = { "MacroPopupFrame" },
			addon = "Blizzard_MacroUI",
			defaultEnabled = true,
		},
		{
			id = "AddonList",
			label = "Addon List",
			group = "system",
			names = { "AddonList" },
			defaultEnabled = true,
		},
		{
			id = "CatalogShopFrame",
			label = "Blizzard Shop",
			group = "system",
			names = { "CatalogShopFrame" },
			defaultEnabled = true,
		},
		{
			id = "AchievementFrame",
			label = "Achievements",
			group = "character",
			names = { "AchievementFrame" },
			addon = "Blizzard_AchievementUI",
			handlesRelative = { "Header" },
			defaultEnabled = true,
		},
		{
			id = "HousingControlsFrame",
			label = "Housing Controls",
			group = "housing",
			names = { "HousingControlsFrame" },
			addon = "Blizzard_HousingControls",
			handlesRelative = { "OwnerControlFrame" },
			defaultEnabled = true,
		},
		{
			id = "HousingDashboardFrame",
			label = "Housing Dashboard",
			group = "housing",
			names = { "HousingDashboardFrame" },
			addon = "Blizzard_HousingDashboard",
			defaultEnabled = true,
		},
		{
			id = "HouseFinderFrame",
			label = "House Finder",
			group = "housing",
			names = { "HouseFinderFrame" },
			addon = "Blizzard_HousingHouseFinder",
			defaultEnabled = true,
		},
		{
			id = "HouseListFrame",
			label = "House List",
			group = "housing",
			names = { "HouseListFrame" },
			addon = "Blizzard_HouseList",
			defaultEnabled = true,
		},
		{
			id = "HousingHouseSettingsFrame",
			label = "Housing Settings",
			group = "housing",
			names = { "HousingHouseSettingsFrame" },
			addon = "Blizzard_HousingHouseSettings",
			defaultEnabled = true,
		},
		{
			id = "AbandonHouseConfirmationDialog",
			label = "Abandon House",
			group = "housing",
			names = { "AbandonHouseConfirmationDialog" },
			addon = "Blizzard_HousingHouseSettings",
			defaultEnabled = true,
		},
		{
			id = "HousingCornerstoneVisitorFrame",
			label = "Housing Cornerstone Visitor",
			group = "housing",
			names = { "HousingCornerstoneVisitorFrame", "HousingCornerstoneHouseInfoFrame" },
			addon = "Blizzard_HousingCornerstone",
			defaultEnabled = true,
		},
		{
			id = "HousingModelPreviewFrame",
			label = "Housing Model Preview",
			group = "housing",
			names = { "HousingModelPreviewFrame" },
			addon = "Blizzard_HousingModelPreview",
			defaultEnabled = true,
		},
		{
			id = "CharacterFrame",
			label = "Character",
			group = "character",
			names = { "CharacterFrame" },
			defaultEnabled = true,
		},
		{
			id = "CooldownViewerSettings",
			label = HUD_EDIT_MODE_COOLDOWN_VIEWER_OPTIONS,
			group = "character",
			names = { "CooldownViewerSettings" },
			addon = "Blizzard_CooldownViewer",
			defaultEnabled = true,
		},
		{
			id = "InspectFrame",
			label = INSPECT,
			group = "character",
			names = { "InspectFrame" },
			defaultEnabled = true,
			addon = "Blizzard_InspectUI",
		},
		{
			id = "PlayerSpellsFrame",
			label = "Talents & Spells",
			group = "character",
			names = { "PlayerSpellsFrame" },
			handlesRelative = { "TalentsFrame", "TalentsFrame.ButtonsParent", "SpecFrame" },
			addon = "Blizzard_PlayerSpells",
			defaultEnabled = true,
		},
		{
			id = "HeroTalentsSelectionDialog",
			label = "Hero Talents",
			group = "character",
			names = { "HeroTalentsSelectionDialog" },
			addon = "Blizzard_PlayerSpells",
			defaultEnabled = true,
		},
		{
			id = "PVEFrame",
			label = "Group Finder",
			group = "activities",
			names = { "PVEFrame" },
			defaultEnabled = true,
		},
		{
			id = "PVPMatchResults",
			label = "PvP Match Results",
			group = "activities",
			names = { "PVPMatchResults" },
			addon = "Blizzard_PVPMatch",
			defaultEnabled = true,
		},
		{
			id = "QueueStatusButton",
			label = "Queue Status Button",
			group = "activities",
			names = { "QueueStatusButton" },
			addon = "Blizzard_QueueStatusFrame",
			skipOnHide = true,
			defaultEnabled = false,
		},
		{
			id = "EncounterJournal",
			label = ADVENTURE_JOURNAL,
			group = "activities",
			names = { "EncounterJournal" },
			addon = "Blizzard_EncounterJournal",
			defaultEnabled = true,
		},
		{
			id = "LFGDungeonReadyDialog",
			label = "Dungeon Ready Dialog",
			group = "activities",
			names = { "LFGDungeonReadyDialog" },
			defaultEnabled = true,
		},
		{
			id = "LFGListInviteDialog",
			label = "LFG List Invite Dialog",
			group = "activities",
			names = { "LFGListInviteDialog" },
			defaultEnabled = true,
		},
		{
			id = "ReadyCheckFrame",
			label = "Ready Check",
			group = "activities",
			names = { "ReadyCheckFrame" },
			defaultEnabled = true,
		},
		{
			id = "WeeklyRewardsFrame",
			label = "Great Vault",
			group = "activities",
			names = { "WeeklyRewardsFrame" },
			addon = "Blizzard_WeeklyRewards",
			defaultEnabled = true,
		},
		{
			id = "DelvesCompanionConfigurationFrame",
			label = "Delves Companion",
			group = "activities",
			names = { "DelvesCompanionConfigurationFrame" },
			addon = "Blizzard_DelvesDashboardUI",
			handlesRelative = { "CompanionPortraitFrame" },
			defaultEnabled = true,
		},
		{
			id = "TransmogFrame",
			label = "Transmog Frame",
			group = "system",
			names = { "TransmogFrame" },
			addon = "Blizzard_Transmog",
			defaultEnabled = true,
		},
		{
			id = "DelvesCompanionAbilityListFrame",
			label = "Delves Companion Abilities",
			group = "activities",
			names = { "DelvesCompanionAbilityListFrame" },
			addon = "Blizzard_DelvesDashboardUI",
			defaultEnabled = true,
		},
		{
			id = "ChallengesKeystoneFrame",
			label = "Font of Power",
			group = "activities",
			names = { "ChallengesKeystoneFrame" },
			addon = "Blizzard_ChallengesUI",
			defaultEnabled = true,
		},
		{
			id = "ItemInteractionFrame",
			label = "Catalyst",
			group = "character",
			names = { "ItemInteractionFrame" },
			addon = "Blizzard_ItemInteractionUI",
			defaultEnabled = true,
		},
		{
			id = "PlayerChoiceFrame",
			label = "Player Choice",
			group = "character",
			names = { "PlayerChoiceFrame" },
			addon = "Blizzard_PlayerChoice",
			defaultEnabled = true,
		},
		{
			id = "WorldMapFrame",
			label = "World Map",
			group = "world",
			names = { "WorldMapFrame" },
			defaultEnabled = true,
		},
		{
			id = "BattlefieldMapFrame",
			label = BATTLEFIELD_MINIMAP,
			group = "world",
			names = { "BattlefieldMapFrame" },
			addon = "Blizzard_BattlefieldMap",
			disableMove = true,
			scaleTargets = { "BattlefieldMapTab" },
			defaultEnabled = true,
		},
		{
			id = "UIWidgetBelowMinimapContainerFrame",
			label = "Below Minimap Widgets",
			group = "world",
			names = { "UIWidgetBelowMinimapContainerFrame" },
			addon = "Blizzard_UIWidgets",
			ignoreFramePositionManager = true,
			defaultEnabled = false,
		},
		{
			id = "UIWidgetPowerBarContainerFrame",
			label = "Power Bar Widgets",
			group = "world",
			names = { "UIWidgetPowerBarContainerFrame" },
			addon = "Blizzard_UIWidgets",
			defaultEnabled = false,
		},
		{
			id = "UIWidgetTopCenterContainerFrame",
			label = "Top Center Widgets",
			group = "world",
			names = { "UIWidgetTopCenterContainerFrame" },
			addon = "Blizzard_UIWidgets",
			defaultEnabled = false,
		},
		{
			id = "FlightMapFrame",
			label = "Flight Map",
			group = "world",
			names = { "FlightMapFrame" },
			addon = "Blizzard_FlightMap",
			defaultEnabled = true,
		},
		{
			id = "ContainerFrameCombinedBags",
			label = "Combined Bags",
			group = "bags",
			names = { "ContainerFrameCombinedBags" },
			defaultEnabled = true,
		},
		{
			id = "ItemUpgradeFrame",
			label = "Item Upgrade",
			group = "vendors",
			names = { "ItemUpgradeFrame" },
			addon = "Blizzard_ItemUpgradeUI",
			defaultEnabled = true,
		},
		{
			id = "ItemSocketingFrame",
			label = ITEM_SOCKETING,
			group = "vendors",
			names = { "ItemSocketingFrame" },
			addon = "Blizzard_ItemSocketingUI",
			defaultEnabled = true,
		},
		{
			id = "ExpansionLandingPage",
			label = "Expansion Landing Page",
			group = "activities",
			names = { "ExpansionLandingPage" },
			addon = "Blizzard_MajorFactions",
			defaultEnabled = true,
		},
		{
			id = "MajorFactionRenownFrame",
			label = "Renown",
			group = "activities",
			names = { "MajorFactionRenownFrame" },
			handlesRelative = { "HeaderFrame" },
			addon = "Blizzard_MajorFactions",
			defaultEnabled = true,
		},
		{
			id = "ProfessionsCustomerOrdersFrame",
			label = "Customer Orders",
			group = "professions",
			names = { "ProfessionsCustomerOrdersFrame" },
			addon = "Blizzard_ProfessionsCustomerOrders",
			defaultEnabled = true,
		},
		{
			id = "MerchantFrame",
			label = "Merchant",
			group = "vendors",
			names = { "MerchantFrame" },
			defaultEnabled = true,
			ignoreFramePositionManager = true,
			userPlaced = true,
		},
		{
			id = "AuctionHouseFrame",
			label = "Auction House",
			group = "vendors",
			names = { "AuctionHouseFrame" },
			addon = "Blizzard_AuctionHouseUI",
			defaultEnabled = true,
		},
		{
			id = "CurrencyTransferMenu",
			label = "Currency Transfer",
			group = "vendors",
			names = { "CurrencyTransferMenu" },
			addon = "Blizzard_TokenUI",
			defaultEnabled = true,
		},
		{
			id = "MailFrame",
			label = "Mail",
			group = "vendors",
			names = { "MailFrame" },
			addon = "Blizzard_MailFrame",
			useRootHandle = true,
			handles = { "SendMailFrame", "MailFrameInset" },
			defaultEnabled = true,
		},
		{
			id = "OpenMailFrame",
			label = "Open Mail",
			group = "vendors",
			names = { "OpenMailFrame" },
			addon = "Blizzard_MailFrame",
			useRootHandle = true,
			handles = { "OpenMailSender", "OpenMailFrameInset" },
			defaultEnabled = true,
		},
		{
			id = "ChatConfigFrame",
			label = "Chat Settings",
			group = "system",
			names = { "ChatConfigFrame" },
			defaultEnabled = true,
		},
		{
			id = "HelpFrame",
			label = "Support",
			group = "system",
			names = { "HelpFrame" },
			addon = "Blizzard_HelpFrame",
			defaultEnabled = true,
		},
		{
			id = "GarrisonCapacitiveDisplayFrame",
			label = "Garrison",
			group = "activities",
			names = { "GarrisonCapacitiveDisplayFrame" },
			addon = "Blizzard_GarrisonUI",
			defaultEnabled = true,
		},
		{
			id = "DressUpFrame",
			label = "Dressing Room",
			group = "character",
			names = { "DressUpFrame" },
			defaultEnabled = true,
		},
		{
			id = "CommunitiesFrame",
			label = "Communities",
			group = "activities",
			names = { "CommunitiesFrame" },
			addon = "Blizzard_Communities",
			defaultEnabled = true,
		},
		{
			id = "ClubFinderCommunityAndGuildFinderFrame",
			label = "Community & Guild Finder",
			group = "activities",
			names = { "ClubFinderCommunityAndGuildFinderFrame.RequestToJoinFrame" },
			addon = "Blizzard_Communities",
			defaultEnabled = true,
		},
		{
			id = "ClubFinderGuildFinderFrame",
			label = "Guild Finder",
			group = "activities",
			names = { "ClubFinderGuildFinderFrame.RequestToJoinFrame" },
			addon = "Blizzard_Communities",
			defaultEnabled = true,
		},
		{
			id = "CommunitiesGuildLogFrame",
			label = "Guild Log",
			group = "activities",
			names = { "CommunitiesGuildLogFrame" },
			addon = "Blizzard_Communities",
			defaultEnabled = true,
		},
		{
			id = "CommunitiesGuildNewsFiltersFrame",
			label = "Guild News Filters",
			group = "activities",
			names = { "CommunitiesGuildNewsFiltersFrame" },
			addon = "Blizzard_Communities",
			defaultEnabled = true,
		},
		{
			id = "CommunitiesGuildTextEditFrame",
			label = "Guild Text Edit",
			group = "activities",
			names = { "CommunitiesGuildTextEditFrame" },
			addon = "Blizzard_Communities",
			defaultEnabled = true,
		},
		{
			id = "CommunitiesRecruitmentDialog",
			label = "Community Recruitment",
			group = "activities",
			names = { "CommunitiesFrame.RecruitmentDialog" },
			addon = "Blizzard_Communities",
			defaultEnabled = true,
		},
		{
			id = "CommunitiesNotificationSettingsDialog",
			label = "Community Notification Settings",
			group = "activities",
			names = { "CommunitiesFrame.NotificationSettingsDialog" },
			addon = "Blizzard_Communities",
			defaultEnabled = true,
		},
		{
			id = "FriendsFrame",
			label = "Friends",
			group = "activities",
			names = { "FriendsFrame" },
			defaultEnabled = true,
		},
		{
			id = "FriendsFrameIgnoreList",
			label = "Ignore List",
			group = "activities",
			names = { "FriendsFrame.IgnoreListWindow" },
			defaultEnabled = true,
		},
		{
			id = "RecruitAFriendRewardsFrame",
			label = "Recruit A Friend Rewards",
			group = "activities",
			names = { "RecruitAFriendRewardsFrame" },
			defaultEnabled = true,
		},
		{
			id = "RecruitAFriendRecruitmentFrame",
			label = "Recruit A Friend",
			group = "activities",
			names = { "RecruitAFriendRecruitmentFrame" },
			defaultEnabled = true,
		},
		{
			id = "FriendsFriendsFrame",
			label = "Friends List",
			group = "activities",
			names = { "FriendsFriendsFrame" },
			defaultEnabled = true,
		},
		{
			id = "RaidInfoFrame",
			label = "Raid Info",
			group = "activities",
			names = { "RaidInfoFrame" },
			defaultEnabled = true,
		},
		{
			id = "AddFriendFrame",
			label = "Add Friend",
			group = "activities",
			names = { "AddFriendFrame" },
			defaultEnabled = true,
		},
		{
			id = "ClassTrainerFrame",
			label = MINIMAP_TRACKING_TRAINER_CLASS,
			group = "world",
			names = { "ClassTrainerFrame" },
			addon = "Blizzard_TrainerUI",
			defaultEnabled = true,
		},
		{
			id = "BankFrame",
			label = "Bank",
			group = "bags",
			names = { "BankFrame" },
			defaultEnabled = true,
		},
		{
			id = "ArtifactFrame",
			label = "Artifact",
			group = "character",
			names = { "ArtifactFrame" },
			addon = "Blizzard_ArtifactUI",
			defaultEnabled = true,
		},
		{
			id = "CollectionsJournal",
			label = "Collections",
			group = "character",
			names = { "CollectionsJournal" },
			addon = "Blizzard_Collections",
			defaultEnabled = true,
		},
		{
			id = "ProfessionsFrame",
			label = "Professions",
			group = "professions",
			names = { "ProfessionsFrame" },
			addon = "Blizzard_Professions",
			defaultEnabled = true,
		},
		{
			id = "ProfessionsBookFrame",
			label = "Professions Book",
			group = "professions",
			names = { "ProfessionsBookFrame" },
			addon = "Blizzard_ProfessionsBook",
			defaultEnabled = true,
		},
		{
			id = "QuestFrame",
			label = "Quest",
			group = "world",
			names = { "QuestFrame", "GossipFrame" },
			defaultEnabled = true,
		},
		{
			id = "StaticPopup",
			label = "Static Popups",
			group = "system",
			names = { "StaticPopup1", "StaticPopup2", "StaticPopup3", "StaticPopup4", "StaticPopup5" },
			defaultEnabled = true,
		},
		{
			id = "EventToastManagerFrame",
			label = "Event Toasts",
			group = "system",
			names = { "EventToastManagerFrame" },
			defaultEnabled = true,
		},
		{
			id = "CalendarFrame",
			label = "Calendar",
			group = "system",
			names = { "CalendarFrame" },
			addon = "Blizzard_Calendar",
			defaultEnabled = true,
		},
		{
			id = "CalendarViewHolidayFrame",
			label = "Calendar Holiday",
			group = "system",
			names = { "CalendarViewHolidayFrame" },
			addon = "Blizzard_Calendar",
			defaultEnabled = true,
		},
		{
			id = "CalendarCreateEventFrame",
			label = "Calendar Event",
			group = "system",
			names = { "CalendarCreateEventFrame" },
			addon = "Blizzard_Calendar",
			defaultEnabled = true,
		},
		{
			id = "TimeManagerFrame",
			label = "Time Manager",
			group = "system",
			names = { "TimeManagerFrame" },
			addon = "Blizzard_TimeManager",
			defaultEnabled = true,
		},
		{
			id = "CovenantSanctumFrame",
			label = "Covenant Sanctum Frame",
			group = "activities",
			names = { "CovenantSanctumFrame" },
			addon = "Blizzard_CovenantSanctum",
			defaultEnabled = true,
		},
		{
			id = "CovenantMissionFrame",
			label = "Covenant Mission Frame",
			group = "activities",
			names = { "CovenantMissionFrame" },
			addon = "Blizzard_GarrisonUI",
			defaultEnabled = true,
		},
		{
			id = "CovenantRenownFrame",
			label = "Covenant Renown Frame",
			group = "activities",
			names = { "CovenantRenownFrame" },
			addon = "Blizzard_CovenantRenown",
			defaultEnabled = true,
		},
		{
			id = "CovenantPreviewFrame",
			label = "Covenant Preview Frame",
			group = "activities",
			names = { "CovenantPreviewFrame" },
			addon = "Blizzard_CovenantPreviewUI",
			defaultEnabled = true,
		},
		{
			id = "GarrisonLandingPage",
			label = "Garrison Landing Page",
			group = "activities",
			names = { "GarrisonLandingPage" },
			addon = "Blizzard_GarrisonUI",
			defaultEnabled = true,
		},
	}
}
