local ADDON_NAME, ns = ...

---------------------------------------------------------------------------
-- Lazy new-profile seed.
--
-- The shipped defaults live ONLY in the compressed Starter Profile export
-- string (importstrings/starter_profile.lua, root TOC) — the former 347 KB
-- literal table paid its parse+alloc on EVERY login; the decode below runs
-- once, at first profile creation / floor reseed, and most logins never
-- pay it at all.
--
-- The string is generated by tools/gen_new_profile_seed.lua and is ALREADY
-- stripped (every "_"-prefixed meta/latch key at any depth + fpsBackup;
-- orphan CDM container satellites purged) — no runtime scrubbing here. A
-- seeded profile still reads as unmigrated (stored schema 0) and the
-- migration layer stamps _schemaVersion/_defaultsVersion afterwards.
--
-- Payload shape (tools/gen_new_profile_seed.lua): seed keys at top level
-- plus a _quiBundledGlobals block, dropped on decode.
--
-- Applied to EVERY newly-created profile (and a fresh install's Default)
-- via the AceDB OnNewProfile hook in core/init.lua. Existing profiles are
-- never touched; copies keep their source. defaults.lua stays the legacy
-- fallback so the shadow-defaults pin (core/compatibility.lua) sees no
-- diff for existing users.
---------------------------------------------------------------------------

local decodedSeed

local function LoadStarterEntry()
    if QUI and QUI.imports then
        local entry = QUI.imports.StarterProfile
        if entry ~= nil then return entry end
    end
    local loaders = QUI and QUI._importLoaders
    local loader = loaders and loaders.StarterProfile
    if type(loader) == "function" then
        return loader()
    end
    return nil
end

local function DecodeSeed()
    local AceSerializer = LibStub and LibStub("AceSerializer-3.0", true)
    local LibDeflate = LibStub and LibStub("LibDeflate", true)
    if not (AceSerializer and LibDeflate) then
        return nil, "AceSerializer-3.0/LibDeflate unavailable"
    end

    local entry = LoadStarterEntry()
    local str = type(entry) == "table" and entry.data or entry
    if type(str) ~= "string" then
        return nil, "Starter Profile import string missing"
    end

    str = str:gsub("%s+", "")
    local prefix = str:match("^([A-Za-z][A-Za-z0-9]*%d):")
    if prefix then
        str = str:sub(#prefix + 2)
    end

    local compressed = LibDeflate:DecodeForPrint(str)
    if not compressed then
        return nil, "starter seed string corrupt (decode)"
    end
    local serialized = LibDeflate:DecompressDeflate(compressed)
    if not serialized then
        return nil, "starter seed string corrupt (decompress)"
    end
    local ok, payload = AceSerializer:Deserialize(serialized)
    if not ok or type(payload) ~= "table" then
        return nil, "starter seed string corrupt (deserialize)"
    end

    payload._quiBundledGlobals = nil
    return payload
end

function ns.GetNewProfileSeed()
    if decodedSeed == nil then
        local seed, err = DecodeSeed()
        if not seed then
            local report = ("QUI: Starter Profile seed decode failed (%s); new profiles keep legacy defaults"):format(err or "?")
            if geterrorhandler then
                geterrorhandler()(report)
            else
                print(report)
            end
            decodedSeed = false
        else
            decodedSeed = seed
        end
    end
    return decodedSeed or nil
end

local function DeepApply(dst, src)
    for k, v in pairs(src) do
        if type(v) == "table" then
            local d = dst[k]
            if type(d) ~= "table" then d = {}; dst[k] = d end
            DeepApply(d, v)
        else
            dst[k] = v
        end
    end
end

function ns.ApplyNewProfileSeed(profile)
    if type(profile) ~= "table" then return end
    local seed = ns.GetNewProfileSeed()
    if not seed then return end
    DeepApply(profile, seed)
end
