-- QUI i18n key extractor.
--   lua5.1 tools/i18n/extract_strings.lua   -> regenerate core/locale/enUS.lua
--   loadfile(...)() returns a module table for unit tests.
local M = {}
local loadString = loadstring or load

-- Find OUR locale keys in a source string: explicit `ns.L["..."]` ONLY.
-- The bareword name `L` is heavily overloaded in this codebase (`local L = MakeLayout(...)`,
-- `local L = {}`, etc.), so localization deliberately uses the fully-qualified `ns.L[...]`.
-- Ignores `ns.L[var]` (dynamic) and any foreign `Foo.L["..."]` / bareword `L["..."]`.
local function decodeLiteral(quote, body)
    local chunk, err = loadString("return " .. quote .. body .. quote)
    if not chunk then
        error("invalid ns.L string literal: " .. tostring(err))
    end
    local ok, value = pcall(chunk)
    if not ok then
        error("invalid ns.L string literal: " .. tostring(value))
    end
    return value
end

function M.collectKeys(src)
    local keys = {}
    for quote, body in src:gmatch("ns%.L%[%s*([\"'])(.-)%1%s*%]") do
        keys[decodeLiteral(quote, body)] = true
    end
    return keys
end

-- Run as a script (deterministic guard via arg[0]); skipped when loadfile()'d in tests.
if arg and arg[0] and arg[0]:match("extract_strings%.lua$") then
    local handle = io.popen("git ls-files '*.lua'")
    local all = {}
    for path in handle:lines() do
        if not path:match("^libs/") and not path:match("^tools/")
           and not path:match("^tests/") and not path:match("search_cache%.lua$") then
            local f = io.open(path, "r")
            if f then
                for k in pairs(M.collectKeys(f:read("*a"))) do all[k] = true end
                f:close()
            end
        end
    end
    handle:close()
    local sorted = {}
    for k in pairs(all) do sorted[#sorted+1] = k end
    table.sort(sorted)
    -- An ordered ARRAY of keys, not a keyed identity table. The old shape
    -- wrote every key twice ([k] = k) for a mapping that carried no
    -- information beyond the key ORDER -- and the order is the whole point:
    -- it IS the ID assignment the ten positional core/locale/<loc>.lua
    -- overlays index into (translation N belongs to keys[N]).
    --
    -- The `-- keyset: <hex>` fingerprint of this array is stamped in
    -- afterwards by tools/i18n/stamp_enus_keyset.py; Lua 5.1 here has no
    -- SHA-256, and keyset_checksum() must have exactly one implementation.
    -- Anything that runs this script must run that one too, or the ten
    -- overlays' checksums have nothing to compare against.
    local out = { "local ADDON_NAME, ns = ...",
        "-- GENERATED by tools/i18n/extract_strings.lua - do not edit by hand.",
        "ns.LocaleData = ns.LocaleData or {}",
        "ns.LocaleData.keys = {" }
    for _, k in ipairs(sorted) do
        out[#out+1] = ("    %q,"):format(k)
    end
    out[#out+1] = "}\n"
    local fe = assert(io.open("core/locale/enUS.lua", "w"))
    fe:write(table.concat(out, "\n")); fe:close()
    io.stderr:write(("extracted %d keys\n"):format(#sorted))
end

return M
