#!/usr/bin/env python3
"""Stamp the `-- keyset: <hex>` checksum line into core/locale/enUS.lua.

`core/locale/enUS.lua` is written by `tools/i18n/extract_strings.lua`, a Lua
script. Lua 5.1 has no SHA-256 in its standard library and none is vendored
in `libs/` (checked), so computing the checksum there would mean either
vendoring a second hash implementation or shelling out from Lua to get one --
both rejected: the whole point of `keyset_checksum` is that it has exactly
ONE implementation, shared by every writer, so enUS and every overlay are
provably comparing the same fingerprint of the same algorithm.

So the header line moves to the Python side instead. Two call sites:
  - `tools/i18n/gen_all_caches.sh` runs `extract_strings.lua` then this
    script, for that script's own regenerate-enUS flow;
  - Task 3 Step 8 calls this script directly, between `extract_strings.lua`
    and the overlay migration -- `gen_all_caches.sh` does not run at that
    point in the plan, so this script must work standalone.

FIX ROUND 1: the first version of this file read enUS's keys via
`translate_delta.read_enus()`. That is the exact Python regex whose newline
blind spot is documented below and in that function's own docstring --
`read_enus()`'s
`(?!quote).` alternative requires `.` to match "any character," but Python's
`.` does not match a literal newline without `re.DOTALL`, and Lua's `%q`
formatter escapes an embedded newline character as a literal backslash
followed by an ACTUAL newline byte, not the two-character escape sequence.
That regex undercounts this
file's true key set (5721 vs the authoritative 5728), so a checksum built
from it would never match a checksum built from the real 5728 -- exactly the
silent-corruption class this whole task exists to prevent, self-inflicted.
Fixed by never regexing the file again: every key set below is read by
loading the real file through Lua, the way the WoW client does.

Handles BOTH shapes `core/locale/enUS.lua` can currently be in, since this
script's own call sites span both moments:
  - the POST-Task-3 shape, `ns.LocaleData.keys` (an ordered array) -- read by
    importing and calling `translate_delta.read_enus_keys()` AS-IS. That
    function is not reimplemented here: this is the "one implementation of
    the loader" the fix asked for, for that shape. It is imported from
    `translate_delta`, which DEFINES it. It used to be imported from
    `tools/i18n/migrate_overlays_positional.py`, which merely re-exported it
    -- that indirection put a spent one-shot on the import path of live,
    release-critical tooling (tools/test.sh, lua-tests.yml,
    regen-i18n-base.yml, gen_all_caches.sh and so release.yml's gates
    barrier), so deleting the one-shot -- the obvious cleanup -- would have
    broken all of them.
  - TODAY's shape (pre-Task-3), `ns.LocaleData.enUS` (a keyed identity map,
    `[key] = key` on every row) -- the array reader above does not, and was
    never meant to, cover this shape (it asserts on `ns.LocaleData.keys` and
    raises when that table is absent), so a second Lua query below reads it
    via `pairs()`. This is a different table under a different name, not a
    second implementation of the array reader.

`read_enus_keys()` tries the array shape first and falls back to the keyed
map on failure, so it works unmodified across the Task 2 -> Task 3 boundary.

Idempotent: reruns replace an existing `-- keyset:` line rather than
duplicating it, so this is safe to invoke standalone, more than once, against
the same enUS.lua.

Usage: python3 tools/i18n/stamp_enus_keyset.py
(no arguments -- it always targets core/locale/enUS.lua)
"""
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from translate_delta import (  # noqa: E402
    ENUS, keyset_checksum, lua_bin, read_enus_keys as _read_enus_keys_array,
)

# Matches the generator banner line emitted by extract_strings.lua, plus an
# already-stamped keyset line if a previous run of this script left one --
# so a rerun replaces it instead of stacking a second copy.
BANNER = re.compile(r"(-- GENERATED by [^\n]*\n)(?:-- keyset: [0-9a-f]+\n)?")


def _read_enus_keys_keyed_map():
    """TODAY's (pre-Task-3) shape: `ns.LocaleData.enUS`, a keyed identity map.

    Loaded via Lua, same as the array reader -- see the module docstring for
    why this must not be a Python regex. The interpreter is resolved by
    translate_delta.lua_bin() ($LUA, then lua5.1, then lua): CI's
    leafo/gh-actions-lua installs `lua` only, so a hardcoded "lua5.1" here
    fails every run that does not apt-get one for itself.
    """
    proc = subprocess.run(
        [lua_bin(), "-e",
         f'local ns = {{}}; assert(loadfile("{ENUS}"))("QUI", ns);'
         'local t = ns.LocaleData and ns.LocaleData.enUS;'
         f'assert(type(t) == "table" and next(t), '
         f'"{ENUS}: ns.LocaleData.enUS is missing or empty");'
         'for k in pairs(t) do '
         'assert(not k:find("\\0", 1, true), "a key contains a literal NUL byte");'
         'io.write(k, "\\0") '
         'end'],
        capture_output=True, text=True, encoding="utf-8")
    if proc.returncode != 0:
        raise SystemExit(f"reading {ENUS} keys (keyed-map shape) via {lua_bin()} failed:\n{proc.stderr}")
    keys = proc.stdout.split("\0")
    if keys and keys[-1] == "":
        keys.pop()
    return keys


def read_enus_keys():
    """Read enUS's key set, whichever of the two known shapes is on disk."""
    try:
        return _read_enus_keys_array()
    except SystemExit as array_err:
        try:
            return _read_enus_keys_keyed_map()
        except SystemExit as keyed_err:
            raise SystemExit(
                f"{ENUS}: could not read keys under either known shape.\n"
                f"  array shape   (ns.LocaleData.keys): {array_err}\n"
                f"  keyed-map shape (ns.LocaleData.enUS): {keyed_err}")


def compute_checksum():
    """Read-only: returns (checksum, keys) without touching the file on disk."""
    keys = read_enus_keys()
    if len(set(keys)) != len(keys):
        raise SystemExit(f"{ENUS}: duplicate keys in the parsed key set -- refusing to "
                          f"checksum an ambiguous key set")
    keys = sorted(keys)
    return keyset_checksum(keys), keys


def main():
    checksum, keys = compute_checksum()

    text = Path(ENUS).read_text(encoding="utf-8")
    stamped, n = BANNER.subn(rf"\1-- keyset: {checksum}\n", text, count=1)
    if n != 1:
        raise SystemExit(f"{ENUS}: could not find the GENERATED banner line to stamp after")

    Path(ENUS).write_text(stamped, encoding="utf-8")
    print(f"{ENUS}: keyset {checksum} ({len(keys)} keys)")


if __name__ == "__main__":
    main()
