#!/usr/bin/env python3
"""Locale overlays must be byte-identical to what their writer emits today.

The ten core/locale/<locale>.lua files are generated by
tools/i18n/translate_delta.py (or assemble_mt.py, which shares
overlay_source), but no staleness gate covers them: translate_delta needs an
API key, so CI cannot regenerate them the way it regenerates the search cache
and core/locale/enUS.lua.

That leaves one failure mode with no other symptom — the committed files and
the writer drifting apart in FORMAT. It already happened once: the shipped
overlays carried an explanatory comment that overlay_source did not emit, so
the next translation run would have silently dropped it from all ten and the
diff would have looked like unrelated churn.

This reads each committed overlay, reconstructs its key/value pairs, re-emits
them through the real writer, and requires the result to match the file byte
for byte. It proves format parity only — it says nothing about translation
freshness, which is translate_delta's job.

The overlays are POSITIONAL: the file holds translations only, one array slot
per enUS key, with a held `nil,` for every key that has none. So the key text
comes from core/locale/enUS.lua and the values from the overlay, zipped by
index. That zip is load-bearing beyond format parity: enUS's key array is
ordered by Lua's table.sort while overlay_source emits in Python's sorted()
order, and this gate is what proves the two orders still agree. If they ever
diverged, the re-emitted bytes would not match and slot N would stop meaning
key N in the shipped client.

Run: python3 tools/i18n/test_overlay_roundtrip.py
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from translate_delta import (  # noqa: E402
    LOCALES, overlay_path, overlay_source, read_enus_keys, read_overlay,
)


def main():
    failures = []
    enus_keys = read_enus_keys()
    for loc in LOCALES:
        path = overlay_path(loc)
        if not os.path.exists(path):
            failures.append(f"{path}: missing — QUI.toc lists all ten overlays")
            continue

        committed = open(path, encoding="utf-8").read()
        translations = read_overlay(loc, enus_keys)
        if not translations:
            failures.append(f"{path}: no translations parsed")
            continue
        # Every enUS key gets a slot; an untranslated one maps to None and is
        # re-emitted as the same held `nil,` the committed file carries.
        table = {k: translations.get(k) for k in enus_keys}

        regenerated = overlay_source(loc, table, "tools/i18n/translate_delta.py")
        if regenerated == committed:
            print(f"  ok  {path} ({len(translations)} translated / "
                  f"{len(enus_keys)} slots)")
            continue

        detail = f"{path}: differs from what overlay_source emits"
        a, b = committed.splitlines(), regenerated.splitlines()
        for i in range(min(len(a), len(b))):
            if a[i] != b[i]:
                detail += (f"\n        first diff at line {i + 1}"
                           f"\n          committed: {a[i][:90]}"
                           f"\n          writer   : {b[i][:90]}")
                break
        else:
            detail += f"\n        line counts differ: committed {len(a)}, writer {len(b)}"
        failures.append(detail)

    if failures:
        for failure in failures:
            sys.stderr.write("FAIL: " + failure + "\n")
        sys.stderr.write(
            "\nThe committed overlays and tools/i18n/translate_delta.py:overlay_source "
            "have drifted.\nFix the writer, or re-emit the files through it — they must "
            "agree, or the next\ntranslation run rewrites all ten with unrelated changes.\n")
        return 1

    print(f"OK: all {len(LOCALES)} locale overlays match their writer byte for byte")
    return 0


if __name__ == "__main__":
    sys.exit(main())
