#!/usr/bin/env python3
"""QUI i18n delta translator.

Reads core/locale/enUS.lua (identity base) + tools/i18n/state.json, computes the
set of new/changed keys per locale, translates ONLY those via translate_fn,
writes core/locale/<loc>.lua, and updates state.json.

Usage:
  python3 tools/i18n/translate_delta.py --locales deDE,frFR        # real run
  python3 tools/i18n/translate_delta.py --mock --locales deDE      # offline self-test
Model/params for the real translator: see the claude-api skill before wiring.
"""
import argparse, hashlib, importlib, json, os, re, subprocess, sys, tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from tools.i18n.lua_literal import unescape_lua_string

LOCALES = ["deDE","esES","esMX","frFR","itIT","ptBR","ruRU","koKR","zhCN","zhTW"]
ENUS = "core/locale/enUS.lua"
STATE = "tools/i18n/state.json"

def sha1(s): return hashlib.sha1(s.encode("utf-8")).hexdigest()

def read_enus():
    """Parse ['key'] = 'value' identity pairs out of the generated enUS.lua."""
    keys = {}
    txt = open(ENUS, encoding="utf-8").read()
    for m in re.finditer(r'\[(["\'])((?:\\.|(?!\1).)*)\1\]\s*=\s*(["\'])((?:\\.|(?!\3).)*)\3', txt):
        key = unescape_lua_string(m.group(2))
        keys[key] = key  # identity (value == key in enUS)
    return keys

def lua_escape(s): return s.replace("\\","\\\\").replace('"','\\"').replace("\n","\\n")

def write_locale(loc, table):
    os.makedirs("core/locale", exist_ok=True)
    lines = [f'local want = (QUIDB and QUIDB.global and QUIDB.global.selectedLocale) or GetLocale()',
             f'if want ~= "{loc}" then return end',
             "local ADDON_NAME, ns = ...",
             "-- GENERATED by tools/i18n/translate_delta.py — do not edit by hand.",
             "ns.LocaleData = ns.LocaleData or {}",
             "ns.LocaleData.active = {"]
    for k in sorted(table):
        lines.append(f'    ["{lua_escape(k)}"] = "{lua_escape(table[k])}",')
    lines.append("}\n")
    open(f"core/locale/{loc}.lua","w",encoding="utf-8").write("\n".join(lines))

LANG_NAMES = {
    "deDE": "German", "esES": "Spanish (Spain)", "esMX": "Spanish (Latin America)",
    "frFR": "French", "itIT": "Italian", "ptBR": "Portuguese (Brazil)",
    "ruRU": "Russian", "koKR": "Korean", "zhCN": "Simplified Chinese",
    "zhTW": "Traditional Chinese",
}

_TRANSLATE_SYSTEM = (
    "You are a professional localizer for a World of Warcraft addon UI. Translate "
    "each English string into {lang} as it would read in-game. Rules, applied to "
    "every string:\n"
    "- Preserve printf format specifiers EXACTLY and in the SAME COUNT: %1$s, %2$d, "
    "%s, %d, %% etc. You may reorder %1$s/%2$s to fit {lang} grammar, but never add, "
    "drop, or alter a specifier.\n"
    "- Preserve WoW escape sequences verbatim: color codes like |cff60A5FA ... |r, "
    "and |T...|t / |H...|h sequences. Translate the human-readable text around them.\n"
    "- Do NOT translate: WoW slash commands (/qui, /reload), API/CVar tokens, or "
    "proper nouns that ship untranslated in the {lang} WoW client (keep 'QUI').\n"
    "- Keep UI labels terse; match the source register.\n"
    "Return ONLY the translations, in the same order as the input array."
)

def real_translate(loc, items):
    # items: list[str] English -> list[str] translations (order-preserved).
    # Anthropic SDK per the claude-api skill: Opus 4.8, adaptive thinking, batched,
    # structured JSON output, cached system prompt. Requires ANTHROPIC_API_KEY.
    anthropic = importlib.import_module("anthropic")
    client = anthropic.Anthropic()
    model = os.environ.get("QUI_I18N_MODEL", "claude-opus-4-8")
    lang = LANG_NAMES.get(loc, loc)
    system = [{
        "type": "text",
        "text": _TRANSLATE_SYSTEM.format(lang=lang),
        "cache_control": {"type": "ephemeral"},
    }]
    schema = {
        "type": "object",
        "properties": {"translations": {"type": "array", "items": {"type": "string"}}},
        "required": ["translations"],
        "additionalProperties": False,
    }
    out, BATCH = [], 60
    for i in range(0, len(items), BATCH):
        chunk = items[i:i + BATCH]
        resp = client.messages.create(
            model=model,
            max_tokens=16000,
            thinking={"type": "adaptive"},
            output_config={"effort": "low", "format": {"type": "json_schema", "schema": schema}},
            system=system,
            messages=[{"role": "user", "content": json.dumps(chunk, ensure_ascii=False)}],
        )
        text = next(b.text for b in resp.content if b.type == "text")
        got = json.loads(text)["translations"]
        if len(got) != len(chunk):
            raise SystemExit(f"{loc}: batch {i}: expected {len(chunk)} translations, got {len(got)}")
        out.extend(got)
    return out

def mock_translate(loc, items):
    return [f"[{loc}] {s}" for s in items]   # deterministic, offline

def load_existing(loc):
    path = f"core/locale/{loc}.lua"
    if not os.path.exists(path): return {}
    out, txt = {}, open(path, encoding="utf-8").read()
    for m in re.finditer(r'\["((?:\\.|[^"])*)"\]\s*=\s*"((?:\\.|[^"])*)"', txt):
        out[unescape_lua_string(m.group(1))] = unescape_lua_string(m.group(2))
    return out

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--locales", default=",".join(LOCALES))
    ap.add_argument("--mock", action="store_true")
    args = ap.parse_args()
    translate = mock_translate if args.mock else real_translate
    enus = read_enus()
    manifest = {k: sha1(v) for k, v in enus.items()}
    state = json.load(open(STATE)) if os.path.exists(STATE) else {}
    for loc in [l for l in args.locales.split(",") if l]:
        prev = state.get(loc, {})
        existing = load_existing(loc)
        # new or changed (hash differs) OR missing from the locale file (self-heal
        # if state.json and the locale file ever drift out of sync)
        delta = [k for k in enus if prev.get(k) != manifest[k] or k not in existing]
        if delta:
            translations = translate(loc, [enus[k] for k in delta])
            for k, tv in zip(delta, translations):
                existing[k] = tv
        # drop keys no longer in enUS
        existing = {k: v for k, v in existing.items() if k in enus}
        write_locale(loc, existing)

        # Format/escape parity gate (reuses the Lua validator as source of truth).
        pairs = "return {" + "".join(
            f'[{json.dumps(k, ensure_ascii=False)}]={json.dumps(existing[k], ensure_ascii=False)},' for k in existing) + "}"
        with tempfile.NamedTemporaryFile("w", suffix=".lua", delete=False, encoding="utf-8") as tf:
            tf.write(pairs); tf_path = tf.name
        chk = subprocess.run(["lua5.1","-e",
            f'local V=assert(loadfile("tools/i18n/validate_format.lua"))();'
            f'local d=V.validate(assert(loadfile("{tf_path}"))());'
            f'if #d>0 then for _,x in ipairs(d) do io.stderr:write(x.key.."\\n") end os.exit(1) end'],
            capture_output=True, text=True)
        os.unlink(tf_path)
        if chk.returncode != 0:
            raise SystemExit(f"{loc}: format parity drift:\n{chk.stderr}")

        state[loc] = {k: manifest[k] for k in existing}
        print(f"{loc}: {len(delta)} translated, {len(existing)} total", file=sys.stderr)
    json.dump(state, open(STATE,"w"), indent=2, sort_keys=True)

if __name__ == "__main__":
    main()
