--[[
  gen_starter_preset_from_seed.lua

  Regenerate importstrings/starter_profile.lua so the Profiles-tab "Starter
  Profile" preset is encoded straight from core/new_profile_defaults.lua
  (ns.NewProfileSeed) — the SAME data a fresh install seeds onto its first
  profile. This keeps the manual preset and the fresh-install seed from
  drifting apart.

  The seed is the single source of truth: the Starter Profile == the
  new-profile seed. _quiBundledGlobals is emitted empty (the seed carries no
  globals), so the import is profile-only, exactly like a fresh install.

  Run after editing the seed:
    lua tools/gen_starter_preset_from_seed.lua

  Drift is enforced by tests/unit/starter_preset_matches_seed_test.lua.
]]

local function ScriptDir()
    local p = (arg and arg[0]) or ""
    p = p:gsub("\\", "/")
    local dir = p:match("(.*/)")
    if dir == nil or dir == "" then return "./" end
    return dir
end

local env = dofile(ScriptDir() .. "_addon_env.lua")
local ns = env.LoadCore()
local LibDeflate    = LibStub("LibDeflate")
local AceSerializer = LibStub("AceSerializer-3.0")

if type(ns.NewProfileSeed) ~= "table" then
    error("ns.NewProfileSeed missing — check core/new_profile_defaults.lua loaded")
end

-- Build the export payload: every seed key + an empty bundled-globals block
-- (matches the historical preset shape; ApplyImportedGlobals no-ops on empty).
local payload = {}
for k, v in pairs(ns.NewProfileSeed) do payload[k] = v end
payload._quiBundledGlobals = { ncdm_specTrackerSpells = {}, specTrackerSpells = {} }

local serialized = AceSerializer:Serialize(payload)
local compressed = LibDeflate:CompressDeflate(serialized)
local encoded    = "QUI1:" .. LibDeflate:EncodeForPrint(compressed)

-- Pick a long-bracket level that cannot collide with the blob contents.
local bracket = "[["
local close   = "]]"
if encoded:find("]]", 1, true) then bracket, close = "[==[", "]==]" end

local OUT = ScriptDir() .. "../importstrings/starter_profile.lua"
local body = table.concat({
    "-- QUI Starter Profile export string.",
    "-- AUTO-GENERATED by tools/gen_starter_preset_from_seed.lua -- DO NOT EDIT BY HAND.",
    "-- Encoded straight from core/new_profile_defaults.lua (ns.NewProfileSeed) so",
    "-- the Profiles-tab \"Starter Profile\" preset and the fresh-install seed never drift.",
    "-- Regenerate after editing the seed: lua tools/gen_starter_preset_from_seed.lua",
    "-- Drift guard: tests/unit/starter_preset_matches_seed_test.lua",
    "",
    "QUI._importLoaders.StarterProfile = function()",
    "    return {",
    "    name = \"Starter Profile\",",
    "    description = \"QUI starter profile (the shipped new-profile defaults)\",",
    "    data = " .. bracket .. encoded .. close .. ",",
    "    }",
    "end",
    "",
}, "\n")

local f = assert(io.open(OUT, "wb"))
f:write(body)
f:close()
print(("Wrote %s (%d byte blob, %d seed keys)"):format(OUT, #encoded, (function()
    local n = 0; for _ in pairs(ns.NewProfileSeed) do n = n + 1 end; return n
end)()))
