-- generate_event_allowlist.lua
--
-- Emits QUI_Debug/event_allowlist.lua: the set of game events that the QUI
-- suite actually registers. The /qui perf event sniffer registers ONLY these
-- (instead of RegisterAllEvents) so the readout is not drowned by high-
-- frequency events QUI never handles (UNIT_COMBAT, COMBAT_LOG_EVENT_UNFILTERED,
-- COMBAT_TEXT_UPDATE, ...).
--
-- Harvest rules (suite = core/ + QUI_*/, excluding generated search caches):
--   1. Inline literal first arg of RegisterEvent( / RegisterUnitEvent(.
--   2. In any file that ALSO registers via a loop variable
--      (e.g. `for _, ev in ipairs(UI_EVENTS) do f:RegisterEvent(ev) end`),
--      every event-shaped quoted token in that file — picks up the table-
--      defined lists (CHAT_MSG_*, UI_EVENTS, SCAN_EVENTS, ...).
--
-- The sniffer guards each registration: RegisterEvent returns false for
-- protected events and errors on unknown names, so any over-harvested token is
-- dropped at runtime by the client. Over-harvesting is therefore harmless.
--
-- Run:  lua tools/generate_event_allowlist.lua
-- Regen whenever a suite file adds/removes a RegisterEvent call.

local OUTPUT_PATH = "QUI_Debug/event_allowlist.lua"

-- Event-name shape: ALL CAPS, must contain an underscore (filters out unit
-- tokens like "PLAYER"/"TARGET" and anchor points like "LEFT"/"TOPRIGHT").
local EVENT_TOKEN = "([A-Z][A-Z0-9]*_[A-Z0-9_]+)"

-- Events QUI consumes through a NON-frame channel (EventRegistry callbacks) and
-- never registers on a sniffable frame. COMBAT_LOG_EVENT_UNFILTERED is also
-- protected in 12.0 (frame RegisterEvent returns false). The broad file-harvest
-- picks them up as string tokens; strip them so the artifact lists only events
-- the sniffer can actually observe.
local DENY = {
    COMBAT_LOG_EVENT_UNFILTERED = true,
}

local function list_lua_files()
    -- core/ plus every QUI_* addon dir, minus the generated OptionsSearch caches.
    local cmd = [[find core QUI_* -name '*.lua' -not -path '*/QUI_OptionsSearch*' 2>/dev/null]]
    local handle = assert(io.popen(cmd, "r"))
    local files = {}
    for line in handle:lines() do
        files[#files + 1] = line
    end
    handle:close()
    table.sort(files)
    return files
end

local function read_file(path)
    local handle = io.open(path, "r")
    if not handle then return nil end
    local body = handle:read("*a")
    handle:close()
    return body
end

local events = {}
local function add(name)
    if name and name ~= "" and not DENY[name] then events[name] = true end
end

for _, path in ipairs(list_lua_files()) do
    local body = read_file(path)
    if body then
        -- (1) inline literals
        for ev in body:gmatch('RegisterEvent%s*%(%s*["\']' .. EVENT_TOKEN .. '["\']') do
            add(ev)
        end
        for ev in body:gmatch('RegisterUnitEvent%s*%(%s*["\']' .. EVENT_TOKEN .. '["\']') do
            add(ev)
        end

        -- (2) loop-register idiom: RegisterEvent(<identifier>)  — harvest every
        -- event-shaped quoted token in the file (the list lives in a table).
        if body:match('RegisterEvent%s*%(%s*[%a_][%w_]*%s*%)') then
            for ev in body:gmatch('["\']' .. EVENT_TOKEN .. '["\']') do
                add(ev)
            end
        end
    end
end

local sorted = {}
for name in pairs(events) do sorted[#sorted + 1] = name end
table.sort(sorted)

local out = {}
out[#out + 1] = "local _, ns = ..."
out[#out + 1] = "-- AUTO-GENERATED by tools/generate_event_allowlist.lua — DO NOT EDIT."
out[#out + 1] = "-- Suite events the /qui perf sniffer registers; regen on RegisterEvent changes."
out[#out + 1] = "ns.QUI_EventAllowlist = {"
for _, name in ipairs(sorted) do
    out[#out + 1] = string.format("    %q,", name)
end
out[#out + 1] = "}"
out[#out + 1] = ""

local handle = assert(io.open(OUTPUT_PATH, "w"))
handle:write(table.concat(out, "\n"))
handle:close()

print(string.format("Wrote %d events to %s", #sorted, OUTPUT_PATH))
