-- tools/strip_comments.lua
--
-- Lexer-based Lua comment stripper. Reads one file, writes the stripped source
-- to stdout. A regex stripper is not good enough here: `--` appears inside
-- string literals and inside long brackets, and `--[[` / `--[==[` comments span
-- lines, so this walks the source with a real Lua 5.1 lexer and only ever
-- deletes spans the lexer classified as comments.
--
-- Comment forms that are PRESERVED (deliberate, each one is load-bearing):
--   * `-- luacheck: ...`   inline directives — 356 of them declare per-file
--                          globals and ignore codes; deleting them reddens the
--                          luacheck gate.
--   * `---@...`            LSP annotations consumed by the language server.
--   * `-- keyset: <hex>`   the enUS locale fingerprint compared by
--                          tests/unit/locale_keyset_checksum_test.lua.
--   * anything the unit suite anchors on, via the harvested list passed as
--     `--anchors <file>`. Much of the suite slices a region out of a source
--     file between two comment banners and loadstrings it, so those banners are
--     structure, not prose. See tools/strip_comments_anchors.lua.
--   * any contiguous comment block that names itself generated
--     (AUTO-GENERATED / GENERATED by / DO NOT EDIT). Keeping the whole block,
--     not just the marker line, is what lets
--     tools/i18n/stamp_enus_keyset.py re-stamp: its regex requires the
--     `-- GENERATED by` line and the `-- keyset:` line to stay adjacent.
--
-- The file scope this is run over lives in tools/strip_comments.sh.

local KEEP_PATTERNS = {
    "^%-%-+%s*luacheck:",
    "^%-%-%-@",
    "^%-%-+%s*keyset:",
}

local GENERATED_MARKERS = {
    "auto%-?generated",
    "generated by",
    "do not edit",
}

local function longBracketLevel(src, pos)
    if src:sub(pos, pos) ~= "[" then return nil end
    local j = pos + 1
    local level = 0
    while src:sub(j, j) == "=" do
        level = level + 1
        j = j + 1
    end
    if src:sub(j, j) == "[" then return level, j + 1 end
    return nil
end

-- Walk the source and return every comment span as {s, e, multiline}. Strings
-- and long brackets are skipped wholesale so a `--` inside them never counts.
local function lexComments(src)
    local spans, strings, n, i = {}, {}, #src, 1
    while i <= n do
        local c = src:sub(i, i)
        if c == "-" and src:sub(i + 1, i + 1) == "-" then
            local level, bodyStart = longBracketLevel(src, i + 2)
            local stop
            if level then
                local _, closeEnd = src:find("]" .. string.rep("=", level) .. "]", bodyStart, true)
                stop = closeEnd or n
            else
                local nl = src:find("\n", i, true)
                stop = (nl and nl - 1) or n
            end
            spans[#spans + 1] = { s = i, e = stop, multiline = level ~= nil }
            i = stop + 1
        elseif c == '"' or c == "'" then
            local j = i + 1
            while j <= n do
                local ch = src:sub(j, j)
                if ch == "\\" then
                    j = j + 2
                elseif ch == c then
                    j = j + 1
                    break
                elseif ch == "\n" then
                    break
                else
                    j = j + 1
                end
            end
            i = j
        elseif c == "[" then
            local level, bodyStart = longBracketLevel(src, i)
            if level then
                local _, closeEnd = src:find("]" .. string.rep("=", level) .. "]", bodyStart, true)
                strings[#strings + 1] = { s = i, e = closeEnd or n }
                i = (closeEnd or n) + 1
            else
                i = i + 1
            end
        else
            i = i + 1
        end
    end
    return spans, strings
end

local function buildLineIndex(src)
    local starts = { 1 }
    local i = 1
    while true do
        local nl = src:find("\n", i, true)
        if not nl then break end
        starts[#starts + 1] = nl + 1
        i = nl + 1
    end
    return starts
end

local function lineOf(starts, pos)
    local lo, hi = 1, #starts
    while lo < hi do
        local mid = math.floor((lo + hi + 1) / 2)
        if starts[mid] <= pos then lo = mid else hi = mid - 1 end
    end
    return lo
end

local function lineEnd(src, starts, line)
    local nextStart = starts[line + 1]
    if nextStart then return nextStart - 1 end -- index of the '\n'
    return #src
end

local function matchesAny(text, patterns)
    local lowered = text:lower()
    for _, p in ipairs(patterns) do
        if lowered:find(p) then return true end
    end
    return false
end

local function shouldKeepOutright(text)
    for _, p in ipairs(KEEP_PATTERNS) do
        if text:find(p) then return true end
    end
    return false
end

local function annotate(src, spans)
    local starts = buildLineIndex(src)
    for _, sp in ipairs(spans) do
        sp.line = lineOf(starts, sp.s)
        sp.endLine = lineOf(starts, sp.e)
        sp.lineStart = starts[sp.line]
        sp.lineEnd = lineEnd(src, starts, sp.endLine)
        sp.text = src:sub(sp.s, sp.e)
        sp.solo = src:sub(sp.lineStart, sp.s - 1):find("^[ \t]*$") ~= nil
        sp.tail = src:sub(sp.e + 1, sp.lineEnd):find("^[ \t\r]*\n?$") ~= nil
        sp.keep = shouldKeepOutright(sp.text)
    end
    return spans
end

-- Keep every comment a test anchor can reach. The anchors are matched against
-- the WHOLE source rather than one comment at a time, because several of them
-- span two lines ("a rule of dashes, then `-- Force update ToT frame`"), and a
-- comment is kept when it overlaps a match at all.
-- An anchor is treated as a Lua pattern only if it contains a `%`, which is how
-- the tests themselves distinguish the two: a test matching a pattern writes
-- `%-%-`, a test matching text calls find(..., true). Guessing wrong is not a
-- cosmetic error — a banner like "-----------" read as a pattern is a run of
-- nested lazy quantifiers (`-` IS the lazy repeat in Lua patterns) and
-- backtracks for minutes on a 500 KB file.
local function anchorIsPattern(anchor)
    return anchor:find("%%") ~= nil
end

-- Longest run of plain characters in a pattern, used to reject an anchor with
-- one cheap plain find instead of running the pattern over the whole file.
local function literalProbe(anchor)
    local best, cur = "", {}
    local i, n = 1, #anchor
    local function flush()
        local run = table.concat(cur)
        if #run > #best then best = run end
        cur = {}
    end
    while i <= n do
        local c = anchor:sub(i, i)
        if c == "%" then
            local nxt = anchor:sub(i + 1, i + 1)
            if nxt:match("%a") then flush() else cur[#cur + 1] = nxt end
            i = i + 2
        elseif c:match("[%^%$%*%+%-%?%.%(%)%[%]]") then
            flush()
            i = i + 1
        else
            cur[#cur + 1] = c
            i = i + 1
        end
    end
    flush()
    return best
end

local MAX_HITS_PER_ANCHOR = 10000

local function keepTestAnchored(src, spans, anchors)
    if not anchors or #anchors == 0 then return end
    local hits = {}
    for _, anchor in ipairs(anchors) do
        local isPattern = anchorIsPattern(anchor)
        local probe = isPattern and literalProbe(anchor) or anchor
        -- No substantial literal means the anchor is a generic comment regex,
        -- not a pin; the harvester drops those, and skipping here keeps a
        -- hand-edited anchor list from silently turning the strip into a no-op.
        if #probe >= 4 and src:find(probe, 1, true) then
            local init, found = 1, 0
            while init <= #src and found < MAX_HITS_PER_ANCHOR do
                local s, e
                if isPattern then
                    local ok, a, b = pcall(string.find, src, anchor, init)
                    if ok then s, e = a, b end
                    if not s then s, e = src:find(anchor, init, true) end
                else
                    s, e = src:find(anchor, init, true)
                end
                if not s then break end
                found = found + 1
                -- Only the DELIMITER lines of a match are load-bearing. Several
                -- anchors span a whole region ("from this banner .- to that
                -- one") because the test slices the region and loadstrings it —
                -- and loadstring does not care what the interior comments say.
                -- Interior prose a test actually asserts on carries its own
                -- anchor, so it is pinned on its own account.
                local firstLineEnd = src:find("\n", s, true) or #src
                local lastLineStart = 1
                for p = e, s, -1 do
                    if src:sub(p, p) == "\n" then lastLineStart = p + 1 break end
                end
                hits[#hits + 1] = { s, math.min(firstLineEnd, e) }
                if lastLineStart > s then hits[#hits + 1] = { lastLineStart, e } end
                init = (e >= s) and (e + 1) or (s + 1)
            end
        end
    end
    for _, sp in ipairs(spans) do
        if not sp.keep then
            for _, h in ipairs(hits) do
                if sp.s <= h[2] and sp.e >= h[1] then
                    sp.keep = true
                    break
                end
            end
        end
    end
end

-- A comment block is a run of solo (whole-line) comments on consecutive lines.
-- If any line in the block names the file generated, the WHOLE block survives.
local function keepGeneratedBlocks(spans)
    local i = 1
    while i <= #spans do
        if not spans[i].solo then
            i = i + 1
        else
            local j = i
            while j + 1 <= #spans
                and spans[j + 1].solo
                and spans[j + 1].line == spans[j].endLine + 1 do
                j = j + 1
            end
            local generated = false
            for k = i, j do
                if matchesAny(spans[k].text, GENERATED_MARKERS) then
                    generated = true
                    break
                end
            end
            if generated then
                for k = i, j do spans[k].keep = true end
            end
            i = j + 1
        end
    end
end

local function removalRanges(src, spans)
    local ranges = {}
    for _, sp in ipairs(spans) do
        if not sp.keep then
            if sp.solo and sp.tail then
                -- Whole line(s) are comment: delete them, newline included.
                ranges[#ranges + 1] = { sp.lineStart, sp.lineEnd }
            elseif sp.solo then
                -- Long comment that ends with code after it on the last line.
                -- Eat the whitespace it left in front of that code too.
                local e = sp.e
                while e < sp.lineEnd and src:sub(e + 1, e + 1):find("^[ \t]") do
                    e = e + 1
                end
                ranges[#ranges + 1] = { sp.lineStart, e }
            else
                -- Trailing comment: also eat the whitespace that led up to it.
                local s = sp.s
                while s > sp.lineStart and src:sub(s - 1, s - 1):find("^[ \t]") do
                    s = s - 1
                end
                ranges[#ranges + 1] = { s, sp.e }
            end
        end
    end
    return ranges
end

-- `--preserve-lines` mode: blank every comment out in place instead of deleting
-- it, so the result has the exact same number of lines and every statement sits
-- on the line it started on. That is what makes the equivalence proof possible:
-- `luac -s` still dumps each prototype's linedefined/lastlinedefined, so
-- bytecode compares equal only when line numbers are untouched. Prove the lexer
-- against THIS output; the real output is then the same text with blank-only
-- lines dropped, which cannot change meaning.
local function blankRemovals(src, ranges)
    local chars = {}
    for i = 1, #src do chars[i] = src:sub(i, i) end
    for _, r in ipairs(ranges) do
        for i = r[1], math.min(r[2], #src) do
            if chars[i] ~= "\n" then chars[i] = " " end
        end
    end
    return table.concat(chars)
end

local function applyRemovals(src, ranges)
    if #ranges == 0 then return src end
    table.sort(ranges, function(a, b) return a[1] < b[1] end)
    local out, cursor = {}, 1
    for _, r in ipairs(ranges) do
        if r[1] > cursor then out[#out + 1] = src:sub(cursor, r[1] - 1) end
        if r[2] + 1 > cursor then cursor = r[2] + 1 end
    end
    out[#out + 1] = src:sub(cursor)
    return table.concat(out)
end

local function longStringLines(text)
    local _, strings = lexComments(text)
    local protected = {}
    if #strings == 0 then return protected end
    local starts = buildLineIndex(text)
    for _, sp in ipairs(strings) do
        for ln = lineOf(starts, sp.s), lineOf(starts, sp.e) do
            protected[ln] = true
        end
    end
    return protected
end

-- Removing a comment that sat between two blank-line separators leaves a double
-- blank behind. Collapse those, trim trailing whitespace, normalise the ends.
local function tidy(text)
    local protected = longStringLines(text)
    local lines, keep, n = {}, {}, 0
    for line in (text .. "\n"):gmatch("([^\n]*)\n") do
        n = n + 1
        keep[n] = protected[n] == true
        lines[n] = keep[n] and line or (line:gsub("[ \t\r]+$", ""))
    end
    while #lines > 0 and lines[#lines] == "" and not keep[#lines] do
        table.remove(lines); table.remove(keep)
    end
    while #lines > 0 and lines[1] == "" and not keep[1] do
        table.remove(lines, 1); table.remove(keep, 1)
    end

    local out = {}
    for i = 1, #lines do
        if lines[i] ~= "" or keep[i] or out[#out] ~= "" then
            out[#out + 1] = lines[i]
        end
    end
    if #out == 0 then return "" end
    return table.concat(out, "\n") .. "\n"
end

local preserveLines = false
local anchorPath, path
local expectAnchors = false
for _, a in ipairs(arg or {}) do
    if expectAnchors then
        anchorPath = a
        expectAnchors = false
    elseif a == "--preserve-lines" then
        preserveLines = true
    elseif a == "--anchors" then
        expectAnchors = true
    else
        path = a
    end
end

local anchors
if anchorPath then
    anchors = assert((loadstring or load)(
        (assert(io.open(anchorPath, "rb")):read("*a"))
    ))()
end
if not path then
    io.stderr:write("usage: lua tools/strip_comments.lua [--preserve-lines] <file.lua>\n")
    os.exit(2)
end

local fh, err = io.open(path, "rb")
if not fh then
    io.stderr:write("strip_comments: " .. tostring(err) .. "\n")
    os.exit(2)
end
local src = fh:read("*a")
fh:close()

local spans = annotate(src, lexComments(src))
keepTestAnchored(src, spans, anchors)
keepGeneratedBlocks(spans)
local ranges = removalRanges(src, spans)
if preserveLines then
    io.write(blankRemovals(src, ranges))
else
    io.write(tidy(applyRemovals(src, ranges)))
end
